op = {
	id = "fast_travel_limiter", sh = true, gr = {
    	{id = "banner", type = "slide", text = "ui_mcm_fast_travel_limiter_title", size = {512, 50}, spacing = 20},
        {id = "next_travel_inc", type = "track", val = 2, min = 1, max = 168, step = 1, def = 24},
    	{id = "tax_multipler", type = "track", val = 2, min = 0, max = 5, step = 0.2, def = 1},
    }
}

function on_mcm_load()
    return op
end
