-- Original script from xcvb's Guards Spawner by xcvb
-- Improved and optimized logic by Jack Harris

function actor_on_first_update()
	CreateTimeEvent("emission_guard_patch_warmup", "execute_startup_fix", 0.5, execute_startup_fix)
end

function execute_startup_fix()
	local sim = alife()
	local repaired_objects = 0

	for squad_id, _ in pairs(SIMBOARD.squads) do
		local se_squad = sim:object(squad_id)
		if se_squad and se_squad.squad_members then
			for member in se_squad:squad_members() do
				local se_obj = sim:object(member.id)
				if se_obj and se_obj.commander_id and se_obj.scripted_target and type(tonumber(se_obj.scripted_target)) == "number" then
					se_obj.scripted_target = tonumber(se_obj.scripted_target)
					repaired_objects = repaired_objects + 1
				end
			end
		end
	end

	--if repaired_objects > 0 then
	--printf("[GUARD PATCH] -> Startup routine fixed %s corrupted squad save targets.", repaired_objects)
	--end
	return true
end

function catch_emission_end(typ, obj, name)
	if name == "emission_end" then
		--printf("[GUARD PATCH] -> Native 'emission_end' event detected! Waking up to patch guard pathing graphs...")
		fix_all_guards()
	end
end

function fix_all_guards()
	local sim = alife()
	local total_fixed = 0

	for id, _ in pairs(SIMBOARD.squads) do
		local squad = sim:object(id)
		if squad then
			local smart_name = get_guard_smart(squad)
			if smart_name and squad.scripted_target ~= smart_name and (axr_companions.companion_squads[squad.id] == nil) then
				squad.scripted_target = smart_name
				total_fixed = total_fixed + 1
			elseif type(tonumber(squad.scripted_target)) == "number" then
				squad.scripted_target = nil
			end
		end
	end
	--printf("[GUARD PATCH] -> Pathfinding patch complete. Successfully restored %s guards to their outposts.", total_fixed)
end

function get_guard_smart(squad)
	local guard_t = guards_spawner and guards_spawner.guarded_smarts
	if not guard_t then return end

	for smart_name, sq_a in pairs(guard_t) do
		for i = 1, #sq_a do
			if sq_a[i] == squad.id then
				return smart_name
			end
		end
	end
end

function on_game_start()
	RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
	RegisterScriptCallback("actor_on_interaction", catch_emission_end)
end
