function unload_ammo(name)
	if (name ~= "UIInventory") then return end
	
	local inventory = ui_inventory.GUI
	
	if inventory then
		npc = inventory:GetPartner()
		if npc and npc:has_info("npcx_is_companion") then
			local itr = function(npc, item)
				if item and IsWeapon(item) then
					item:set_ammo_elapsed(0)
				end
			end
			npc:iterate_inventory(itr, npc)
		end
	end
end

function on_game_start()
	RegisterScriptCallback("GUI_on_show",unload_ammo)
end