-- oleh5230, 18.11.25
-- Last edit: 09.12.25
debug = false

local timeout_tg = 0
local timeout_duration = 1
local def_timeout_duration = 1

function itms_manager.print_dbg(txt, ...)
	if debug then
		printf("[itms_manager_snd_on_take] " .. txt, ...)
	end
end

-- call this function to temporarily disable pickup sounds
function itms_manager.timeout_snd_on_take(duration)
	timeout_tg = time_global()
	timeout_duration = duration or def_timeout_duration
end

snd_on_take = {
	-- vanilla types:
	["coin"]    			= {"interface\\items\\inv_items_money_coin"},
	["bolt"]    			= {"interface\\items\\inv_items_bolt"},
	["paper"]   			= {"interface\\items\\inv_items_money_paper"},
	["bottle"]   			= {"interface\\items\\inv_items_bottle_",1,2},
	["pills"]   			= {"interface\\items\\inv_items_pills_1"},
	["part"]   				= {"interface\\items\\inv_items_parts_",1,3},
	["outfit"]  			= {"interface\\items\\inv_items_cloth_",1,2},
	["ammo"]    			= {"interface\\items\\inv_items_ammo_",1,3},
	["grenade"] 			= {"interface\\items\\inv_items_grenade_1"},
	["knife"]    			= {"interface\\items\\inv_items_knife_",1,2},
	["weapon"]  			= {"interface\\items\\inv_items_wpn_",1,2},
	["other"]   			= {"interface\\items\\inv_items_generic_",1,2},

	-- Audio Expansion + custom types:
	["addon"]  				= {"interface\\items\\inv_items_addon_1"},
	["ammoshell"]  			= {"interface\\items\\inv_items_ammoshell_",1,3},
	["ammogren"]  			= {"interface\\items\\inv_items_ammogren_1"},
	["magazine"]			= {"interface\\items\\inv_items_mag_1"},
	["magazinebelt"]		= {"interface\\items\\inv_items_magbelt_1"},

	["drinkcan"]  			= {"interface\\items\\inv_items_drinkcan_1"},
	["tincan"]  			= {"interface\\items\\inv_items_tincan_1"},
	["wrap"]				= {"interface\\items\\inv_items_wrap_1"},
	["bottlepoly"]  		= {"interface\\items\\inv_items_bottlepoly_1"},
	["bottlesmall"]			= {"interface\\items\\inv_items_bottlesmall_1"},
	["cigar"]				= {"interface\\items\\inv_items_cigar_1"},
	["bandage"]				= {"interface\\items\\inv_items_bandage_1"},
	["syringe"]  			= {"interface\\items\\inv_items_syringe_1"},
	["blister"]				= {"interface\\items\\inv_items_blister_1"},

	["wood"]				= {"interface\\items\\inv_items_wood_1"},
	["rock"]				= {"interface\\items\\inv_items_rock_",1,2},
	["coal"]				= {"interface\\items\\inv_items_coal_1"},
	["plastic"]				= {"interface\\items\\inv_items_plastic_1"},
	["fabric"]				= {"interface\\items\\inv_items_fabric_",1,2},
	["powder"]				= {"interface\\items\\inv_items_generic_",1,2},

	["junk"]				= {"interface\\items\\inv_items_junk_1"},
	["jar"]  				= {"interface\\items\\inv_items_jar_1"},
	["cont"]				= {"interface\\items\\inv_items_cont_1"},
	["matchbox"]			= {"interface\\items\\inv_items_matchbox_1"},
	["shovel"]  			= {"interface\\items\\inv_items_shovel_1"},
	["jerrycan"]  			= {"interface\\items\\inv_items_jerrycan_1"},
	["jerrycanpoly"]		= {"interface\\items\\inv_items_jerrycanpoly_1"},
	["device"]  			= {"interface\\items\\inv_items_device_1"},
	["book"]				= {"interface\\items\\inv_items_book_1"},
	["tape"]				= {"interface\\items\\inv_items_tape_1"},
	["patch"]				= {"interface\\items\\inv_items_patch_1"},

	["flesh"]  				= {"interface\\items\\inv_items_flesh_",1,2},
	["hide"]  				= {"interface\\items\\inv_items_hide_1"},
	["bone"]				= {"interface\\items\\inv_items_bone_1"},

	["kit"]  				= {"interface\\items\\inv_items_kit_1"},
	["kitpoly"]  			= {"interface\\items\\inv_items_kitpoly_1"},
    ["outfit_equ"]  		= {"interface\\items\\inv_items_outfit_",1,2},
	["helmet_equ"]  		= {"interface\\items\\inv_items_helmet_1"},

	["w_pistol"]			= {"interface\\items\\inv_items_wpnhg_",1,2},
	["w_smg"]				= {"interface\\items\\inv_items_wpn_",1,2},
	["w_rifle"]				= {"interface\\items\\inv_items_wpnbig_",1,2},
	["w_sniper"]			= {"interface\\items\\inv_items_wpnbig_",1,2},
	["w_shotgun"]			= {"interface\\items\\inv_items_wpnbig_",1,2},
	["w_explosive"]			= {"interface\\items\\inv_items_wpnbig_",1,2},

	["woodfurniture"]  		= {"interface\\items\\inv_items_woodfurniture_",1,2},
	["metalfurniture"]  	= {"interface\\items\\inv_items_metalfurniture_",1,2},
}

snd_on_use = {
	["cap"]					= {"interface\\items_use\\cap_1"},

	["glue"]				= {"interface\\items_use\\glue_1"},
	["scissors"]			= {"interface\\items_use\\scissors_1"},
	["tape"]				= {"interface\\items_use\\tape_1"},
	["parts_fabric"]		= {"interface\\items_use\\parts_fabric_1"},

	["oil"]					= {"interface\\items_use\\oil_1"},
	["spray"]				= {"interface\\items_use\\spray_1"},
	["parts_metal"]			= {"interface\\items_use\\parts_metal_1"},

	["clean"]				= {"interface\\items_use\\clean_1"},
	["file"]				= {"interface\\items_use\\file_1"},
	["sharp"]				= {"interface\\items_use\\sharp_1"},
}

local enabled = true
local base_vol = 1

local time_snd_prev = 0
play_item_sound = itms_manager.play_item_sound
function itms_manager.play_item_sound(item, vol)
	if not enabled then return end
	if (not item) then
		printe("!ERROR itms_manager_snd_on_take | play_item_sound | no object recieved!")
		return
	end

	local snd_type = SYS_GetParam(0,item:section(),"snd_on_take")
	if not (snd_type and snd_type ~= "") then
		return
	end

	local snd = snd_on_take[snd_type]
	-- oleh5230
	if snd_type == "weapon" then
		snd = snd_on_take[SYS_GetParam(0,item:section(),"kind") or "w_rifle"]
	end
	-- oleh5230 end
	if (not snd) then
		return
	end

	local snd_obj
	if (#snd == 1) then
		snd_obj = sound_object(snd[1])
	else
		snd_obj = sound_object(snd[1] .. tostring(math.random(snd[2],snd[3])))
	end

	local time_g = time_global()
	itms_manager.print_dbg("itms_manager_snd_on_take timeout: %s %s", time_g, timeout_tg)
	if snd_obj and (time_g > time_snd_prev + 25) and (time_g > timeout_tg + timeout_duration) then
		snd_obj:play(db.actor,0,sound_object.s2d)
		snd_obj.volume = vol and base_vol * vol or base_vol
		timeout_duration = def_timeout_duration
	end
	time_snd_prev = time_g
end

local time_snd_prev2 = 0
function itms_manager.play_use_sound(item, vol)
	if (not item) then
		printe("!ERROR itms_manager_snd_on_take | play_use_sound | no object recieved!")
		return
	end

	local snd_type = SYS_GetParam(0,item:section(),"snd_on_use")
	if not (snd_type and snd_type ~= "") then
		return
	end

	local snd = snd_on_use[snd_type]
	if (not snd) then
		return
	end

	local snd_obj
	if (#snd == 1) then
		snd_obj = sound_object(snd[1])
	else
		snd_obj = sound_object(snd[1] .. tostring(math.random(snd[2],snd[3])))
	end

	local time_g = time_global()
	if snd_obj and (time_g > time_snd_prev2 + 200) then
		snd_obj:play(db.actor,0,sound_object.s2d)
		snd_obj.volume = vol and base_vol * vol or base_vol
	end
	time_snd_prev2 = time_g
end

-- fix for items spawned after opening a container
function GUI_on_show(name)
	if name == "UIInventory" and ui_inventory.GUI and ui_inventory.GUI.mode == "loot" then
		-- increased duration for demonized exes' ammo aggregation
		itms_manager.print_dbg("UIInventory timeout")
		itms_manager.timeout_snd_on_take(250)

	-- elseif name == "UIMutantLoot" and ui_mcm and ui_mcm.get("fddar/skinning/auto_loot_all") then
	-- 	itms_manager.print_dbg("UIMutantLoot timeout")
	-- 	itms_manager.timeout_snd_on_take()
	end
end

function GUI_on_hide(name)
	-- fix for ammo spawned by ammo wheel 
	if name == "UIWheelAmmo" then
		itms_manager.print_dbg("UIWheelAmmo timeout")
		itms_manager.timeout_snd_on_take()

	-- patch for mutant skinning (to not interfere with FDDAR)
	elseif name == "UIMutantLoot" then
		if ui_mcm and ui_mcm.get("fddar/skinning/enable") then
			itms_manager.print_dbg("UIMutantLoot timeout")
			itms_manager.timeout_snd_on_take()
		end
	end
end

-- fix for items spawned upon item use (to not interfere with FDDA)
function actor_on_item_use()
	itms_manager.print_dbg("actor_on_item_use timeout")
	itms_manager.timeout_snd_on_take()
end

-- fix for headgear/backpack equip (to not interfere with FDDAR)
-- unused, fixed in ui_inventory
function actor_item_equip(obj)
	if (IsHeadgear(obj) and ui_mcm and ui_mcm.get("fddar/headgear_anm/enable"))
	or (IsItem("backpack", nil, obj) and ui_mcm and ui_mcm.get("fddar/outfit_anm/enable_backpack_equip")) then
		itms_manager.print_dbg("actor_item_equip timeout")
		itms_manager.timeout_snd_on_take()
	end
end

function load_mcm_options()
    if ui_mcm and oleh_sounds_mcm then
        enabled = ui_mcm.get("oleh_sounds/inventory/enabled_inventory_pickup")
        base_vol = ui_mcm.get("oleh_sounds/inventory/volume_inventory_pickup") or 1
    -- old MCM compatibility
    elseif ui_mcm and oleh_misc_sounds_mcm then
        enabled = ui_mcm.get("oleh_misc_sounds/enabled_inventory_pickup")
        base_vol = ui_mcm.get("oleh_misc_sounds/volume_inventory_pickup") or 1
    end
end

function actor_on_update()
	itms_manager.print_dbg("!%s", timeout_duration)
end

function on_game_start()
	--RegisterScriptCallback("actor_on_update", actor_on_update)
	RegisterScriptCallback("GUI_on_show", GUI_on_show)
	RegisterScriptCallback("GUI_on_hide", GUI_on_hide)
	RegisterScriptCallback("actor_on_item_use", actor_on_item_use)
	--RegisterScriptCallback("actor_item_to_slot", actor_item_equip)
	--RegisterScriptCallback("actor_item_to_ruck", actor_item_equip)
    RegisterScriptCallback("on_option_change", load_mcm_options)
    load_mcm_options()
end