LMode_TakeAll = ui_inventory.UIInventory.LMode_TakeAll
ui_inventory.UIInventory.LMode_TakeAll = function(self)
	itms_manager.timeout_snd_on_take(250)
	utils_obj.play_sound("interface\\inv_move_all")
	LMode_TakeAll(self)
end

LMode_PutAll = ui_inventory.UIInventory.LMode_PutAll
ui_inventory.UIInventory.LMode_PutAll = function(self)
	itms_manager.timeout_snd_on_take(250)
	utils_obj.play_sound("interface\\inv_move_all")
	LMode_PutAll(self)
end