--SERIOUS: This script only exists to prevent the monkey patch that would add the loading back of inventory items to the stash.
-- Monkey patch overwrite: SixSloth's & Veerserif's Hideout Furnitures 2.2.1 GAMMA patch
-- File: zzz_workshop_return_items.script

item_ids = {}
stash_id = nil

ui_workshop_UIWorkshop_Close = ui_workshop.UIWorkshop.Close
ui_workshop.UIWorkshop.Close = function(self)
	ui_workshop_UIWorkshop_Close(self)
end