-- @ Version: SCREEN SPACE SHADERS - UPDATE 22
-- @ Description: Parallax script - Settings
-- @ Author: https://www.moddb.com/members/ascii1457
-- @ Mod: https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders

-- If you're not using MCM you can customize your settings here --

ssfx_default_settings = 
{
	["quality"]			= 16.0,
	["refine"]			= 0,

	["range"]			= 12,
	["height"]			= 0.035,
	["ao"]				= 0.4,
}

----------------------------------------------------