---Мои функции -----

local aditional_spawn_table = {
-- {x, y, z, level_vertex_id, game_vertex_id, кол-во}
--	spawn_bol_o1 = {['af_ah_o1'] = {242.14581298828,5.3199117660522,53.268936157227, 292647, 63}},
	spawn_bol_o1 = {['af_ah_o1'] = {241.87088012695,5.9297779083252,52.383800506592, 293187, 63}},	
	spawn_bol_o2 = {['af_ah_o2'] = {386.03338623047,0.98510533571243,314.71539306641, 400778, 270}},	
	spawn_bol_e1 = {['af_ah_e1'] = {459.04193115234,1.9701368808746,-7.0784845352173, 448532, 246}},
	spawn_agr_pda = {['kovalev_pda_item'] = {47.145408630371,8.4094705581665,-12.874572753906, 238350, 1013}},
	spawn_agr_g1 = {['af_ah_g1'] = {-199.63502502441,0.90268939733505,-28.170597076416, 29987, 943}},
	spawn_agr_g2 = {['af_ah_g2'] = {22.595127105713,6.0576524734497,-275.8801574707, 218591, 1046}},	
	spawn_agr_h1 = {['af_ah_h1'] = {-195.37408447266,1.1277058124542,66.171974182129, 19691, 970}},	

	spawn_yan_o1 = {['af_ah_o1'] = {-174.13641357422,3.2181444168091,-143.85270690918, 5663, 2195}},
	spawn_yan_h1 = {['af_ah_h1'] = {-41.927017211914,-13.217215538025,-246.43304443359, 48764, 2197}},	
	spawn_yan_h2 = {['af_ah_h2'] = {175.21632385254,2.2580873966217,89.942222595215, 147072, 2213}},	
	spawn_dt_o1 = {['af_ah_o1'] = {-126.15940856934,-1.9097385406494,123.05704498291, 41994, 1821}},
	spawn_dt_e1 = {['af_ah_e1'] = {-266.98266601563,3.8934457302094,167.24801635742, 5398, 1851}},	
	spawn_dt_e2 = {['af_ah_e2'] = {-242.76332092285,-5.0310530662537,85.509910583496, 12572, 1892}},	
	spawn_yan_e1 = {['af_ah_e1'] = {88.04581451416,0.9254247546196,-61.850219726563, 108615, 2247}},
	spawn_yan_e2 = {['af_ah_e2'] = {89.392547607422,-0.0059276223182678,-7.53919506073, 108333, 2234}},	
	spawn_yan_g1 = {['af_ah_g1'] = {-0.77743142843246,27.662294387817,-11.827794075012, 68524, 2217}},	

	spawn_td_o1 = {['af_ah_o1'] = {-6.3827834129333,10.674922943115,-179.35498046875, 161161, 1630}},	
	spawn_td_o2 = {['af_ah_o2'] = {126.88205718994,2.4974358081818,-483.04809570313, 309930, 1622}},
	spawn_td_e1 = {['af_ah_e1'] = {121.47485351563,12.745860099792,-49.468452453613, 302078, 1491}},	
	spawn_kt_g1 = {['af_ah_g1'] = {-153.09321594238,-8.7200832366943,-94.427383422852, 243570, 5119}},
	spawn_kt_o1 = {['af_ah_o1'] = {266.24267578125,21.628379821777,-277.0832824707, 797231, 5207}},	
	spawn_kt_h1 = {['af_ah_h1'] = {-301.37066650391,16.750459671021,-121.78722381592, 34211, 5263}},	
	spawn_sv_pda = {['pirogov_pda_item'] = {102.02368164063,-5.1749172210693,156.94705200195, 253604, 645}},
	spawn_sv_g1 = {['af_ah_g1'] = {-255.91717529297,4.1241917610168,98.584175109863, 4340, 692}},	
	spawn_sv_h1 = {['af_ah_h1'] = {106.09580993652,2.1096873283386,-137.30087280273, 237993, 668}},	
		
	spawn_mil_h1 = {['af_ah_h1'] = {104.25748443604,-7.7414011955261,167.05085754395, 372272, 2015}},
	spawn_mil_g1 = {['af_ah_g1'] = {-157.77574157715,-0.27874371409416,10.363350868225, 154022, 2186}},		
	spawn_mil_o1 = {['af_ah_o1'] = {-247.53811645508,-17.218084335327,225.62403869629, 81174, 2130}},		
	spawn_les_pda = {['strelok_pda_item'] = {-76.873001098633,-4.3313798904419,-164.41079711914, 14445, 2792}},
	spawn_les_o1 = {['af_ah_o1'] = {219.65069580078,-7.3071460723877,-94.532341003418, 137835, 2773}},	
	spawn_les_e1 = {['af_ah_e1'] = {-121.0258102417,-5.4002523422241,-42.273204803467, 7481, 2772}},	

	spawn_lim_s1 = {['af_ah_s1'] = {71.559020996094,11.673633575439,256.08560180664, 58203, 2473}},

	spawn_rad_pda = {['chernov_pda_item'] = {662.60522460938,-43.904781341553,171.93785095215, 227308, 2537}},
-- Снорк1	
	spawn_rad_r1 = {['af_ah_r1'] = {470.09167480469,-47.758029937744,-265.94635009766, 156143, 2690}},
-- Вертолет		
	spawn_rad_r2 = {['af_ah_r2'] = {356.06051635742,-39.192668914795,-197.50382995605,  97838, 2723}},	
-- Зомби 2 канон	
	spawn_rad_r3 = {['af_ah_r3'] = {551.74591064453,-48.829395294189,-88.514717102051, 191604, 2667}},	
	spawn_mg_o1 = {['af_ah_o1'] = { -134.83152770996,2.9880950450897,32.194671630859, 55687, 2361}},
	spawn_mg_g1 = {['af_ah_g1'] = {159.51693725586,4.3780035972595,-61.599414825439, 234620, 2332}},	

	spawn_up_g1 = {['af_ah_g1'] = {226.7353515625,12.497895240784,-126.44523620605, 1104135, 4477}},
	spawn_up_h1 = {['af_ah_h1'] = {240.87431335449,16.29806137085,-306.95077514648, 1122230, 4477}},			
	spawn_up_h2 = {['af_ah_h2'] = {82.844253540039,7.2727770805359,19.8655128479, 860122, 4698}},		


	spawn_up_e1 = {['af_ah_e1'] = {-374.17404174805,5.0997858047485,385.88662719727, 115301, 4581}},		
	spawn_up_e2 = {['af_ah_e2'] = {-184.40615844727,5.8987579345703,-66.753799438477, 407076, 4539}},
	spawn_up_g2 = {['af_ah_g2'] = {-409.46270751953,3.3450148105621,9.6419630050659, 31416, 4523}},	

	spawn_p_h1 = {['af_ah_h1'] = {136.44596862793,30.190256118774,239.75834655762, 294108, 5045}},
	spawn_p_g1 = {['af_ah_g1'] = {73.222862243652,10.05225276947,123.31704711914, 293323, 5045}},	
	spawn_p_g2 = {['af_ah_g2'] = {-39.609481811523,2.2897946834564,349.08999633789, 59084, 2946}},	
	spawn_p_e1 = {['af_ah_e1'] = {46.502857208252,-1.7335567474365,-17.505851745605, 159425, 3018}},

	spawn_zat_pda = {['vorobushkin_pda_item'] = {-445.25088500977,6.1879630088806,46.998878479004, 117515, 4151}},
	spawn_zat_h1 = {['af_ah_h1'] = {-399.41204833984,-6.0142226219177,183.90542602539, 183046, 4398}},	
	spawn_zat_h2 = {['af_ah_h2'] = {-316.50579833984,32.358577728271,-159.77275085449, 344948, 4158}},	

	spawn_zat_g1 = {['af_ah_g1'] = {-125.387840271,-7.0910167694092,-225.74705505371, 690469, 4142}},	
	spawn_zat_g2 = {['af_ah_g2'] = {433.74664306641,34.359256744385,-191.26034545898, 1676984, 4172}},
	spawn_zat_o1 = {['af_ah_o1'] = {389.83050537109,0.49227422475815,438.83108520508, 1661766, 4172}},	

	
	spawn_gen_f1 = {['af_ah_f1'] = {11.673232078552,38.033100128174,-232.00248718262, 211717, 3505}}	
}


----Спавн функция ----
local function ah_spawn(name)
	local tbl = aditional_spawn_table[name]
	for k, v in pairs(tbl) do
		for i = 1, (v[6] or 1) do 
			alife():create(k, vector():set(v[1], v[2], v[3]), v[4], v[5])
		end
	end
end

function give_simple_detector(first_speaker, second_speaker) 
      dialogs.relocate_item_section(second_speaker, "detector_simple", "in",1)
end  

function give_expert_detector(first_speaker, second_speaker) 
      dialogs.relocate_item_section(second_speaker, "detector_elite", "in",1) 
end  

function give_ah_gramota(first_speaker, second_speaker) 
      dialogs.relocate_item_section(second_speaker, "ah_gramota", "in",1) 
end  

----Создание фразы для ученых, по линию сюжета----
function create_story_line_phrase()
	local ah_level_counter=1
	if has_alife_info("ahi_kovalev_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	if has_alife_info("ahi_kovalev_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_markov_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_markov_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_markov_3_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_pirogov_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_pirogov_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_pirogov_3_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_chernov_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_chernov_6_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	
	if has_alife_info("ahi_juk_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	if has_alife_info("ahi_juk_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	if has_alife_info("ahi_juk_3_quest_end") then ah_level_counter = ah_level_counter + 1	
	end
	if has_alife_info("ahi_vorobushkin_1_quest_end") then ah_level_counter = ah_level_counter + 1	
	end
	if has_alife_info("ahi_vorobushkin_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	printf("Уровень_"..ah_level_counter)
	if ah_level_counter >= 15 then 
		give_info("ahi_goto_scabinsky")
		printf("Идем к Скабинскому")
	end	
	return game.translate_string("story_line_dialog_"..ah_level_counter)
end



----Создание фразы ответа для гг, по сюжету----
function create_story_line_answer_phrase()
	local ah_level_counter=1
	if has_alife_info("ahi_kovalev_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	if has_alife_info("ahi_kovalev_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_markov_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_markov_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_markov_3_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_pirogov_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_pirogov_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_pirogov_3_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_chernov_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end	
	if has_alife_info("ahi_chernov_6_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	
	if has_alife_info("ahi_juk_1_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	if has_alife_info("ahi_juk_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	if has_alife_info("ahi_juk_3_quest_end") then ah_level_counter = ah_level_counter + 1	
	end
	if has_alife_info("ahi_vorobushkin_1_quest_end") then ah_level_counter = ah_level_counter + 1	
	end
	if has_alife_info("ahi_vorobushkin_2_quest_end") then ah_level_counter = ah_level_counter + 1
	end
	
	return game.translate_string("story_line_answer_"..ah_level_counter)
end


--- Проверяем а в монолите ли игрок ---
function check_community_actor(first_speaker, second_speaker) 
      return (db.actor:character_community() == "actor_monolith" )
--db.actor "monolith"
--if npc:character_community() ~= "(dolg)" then 
--	npc:set_character_community("dolg", 0, 0) 
--end
end


function ah_signal(first_speaker, second_speaker)
---	get_console():execute("Туттиду_БИБИБ") 
--- local se_obj = get_story_se_object( "kovalev_pda_item" )
--- local stash_id = alun_utils.load_var( db.actor, "kovalev_pda_item_id", nil )
	printf("Туттиду_БИБИБ")
	news_manager.send_tip(db.actor,"Quest1_title", nil, "seeker", nil, 3000) 
end



function redirect_give_quest()
	if not has_alife_info("ahi_kovalev_2_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_kovalev_quest_start")
		disable_info("ahi_redirect_kovalev_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_kovalev_quest")         
	elseif not has_alife_info("ahi_markov_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_markov_quest_start")
		disable_info("ahi_redirect_markov_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_markov_quest")  
	elseif not has_alife_info("ahi_pirogov_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_pirogov_quest_start")
		disable_info("ahi_redirect_pirogov_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_pirogov_quest")  
	elseif not has_alife_info("ahi_chernov_6_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_chernov_quest_start")
		disable_info("ahi_redirect_chernov_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_chernov_quest")  
	elseif not has_alife_info("ahi_juk_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_juk_quest_start")
		disable_info("ahi_redirect_juk_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_juk_quest")  
	elseif not has_alife_info("ahi_vorobushkin_2_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_vorobushkin_quest_start")
		disable_info("ahi_redirect_vorobushkin_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_vorobushkin_quest")  
		
	end
end 


function redirect_give_quest_small_revers()
	if not has_alife_info("ahi_chernov_6_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_chernov_quest_start")
		disable_info("ahi_redirect_chernov_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_chernov_quest")  
	elseif not has_alife_info("ahi_pirogov_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_pirogov_quest_start")
		disable_info("ahi_redirect_pirogov_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_pirogov_quest")  
	elseif not has_alife_info("ahi_markov_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_markov_quest_start")
		disable_info("ahi_redirect_markov_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_markov_quest")  
	elseif not has_alife_info("ahi_kovalev_2_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_kovalev_quest_start")
		disable_info("ahi_redirect_kovalev_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_kovalev_quest")      
	elseif not has_alife_info("ahi_juk_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_juk_quest_start")
		disable_info("ahi_redirect_juk_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_juk_quest")  
	elseif not has_alife_info("ahi_vorobushkin_2_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_vorobushkin_quest_start")
		disable_info("ahi_redirect_vorobushkin_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_vorobushkin_quest")  		
	end	
end 


function redirect_give_quest_revers()

	if not has_alife_info("ahi_vorobushkin_2_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_vorobushkin_quest_start")
		disable_info("ahi_redirect_vorobushkin_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_vorobushkin_quest")  
	elseif not has_alife_info("ahi_juk_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_juk_quest_start")
		disable_info("ahi_redirect_juk_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_juk_quest") 
	elseif not has_alife_info("ahi_chernov_6_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_chernov_quest_start")
		disable_info("ahi_redirect_chernov_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_chernov_quest")  
	elseif not has_alife_info("ahi_pirogov_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_pirogov_quest_start")
		disable_info("ahi_redirect_pirogov_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_pirogov_quest")  
	elseif not has_alife_info("ahi_markov_3_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_markov_quest_start")
		disable_info("ahi_redirect_markov_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_markov_quest")  
		
	elseif not has_alife_info("ahi_kovalev_2_quest_end") then
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_kovalev_quest_start")
		disable_info("ahi_redirect_kovalev_quest_end")
        task_manager.get_task_manager():give_task("ah_redirect_to_kovalev_quest")      
	end
end 

function redirect_give_quest_skabinsky()
		give_info("ahi_redirect_quest_inprogress")
		give_info("ahi_redirect_skabinsky_quest_start")
		disable_info("ahi_redirect_skabinsky_quest_end")		
        task_manager.get_task_manager():give_task("ah_redirect_to_skabinsky_quest")
end

function give_fail_quest_skabinsky()
		give_info("ahi_redirect_quest_inprogress")
        task_manager.get_task_manager():give_task("ah_fail_skabinsky_quest")
end

function ah_fail_timer()
		if not has_alife_info("ah_fail_step_1") then 
			give_info("ah_fail_step_1")
			printf("Первая ошибка")
		elseif not has_alife_info("ah_fail_step_2") then 
			give_info("ah_fail_step_2")
			printf("Вторая ошибка")
		elseif not has_alife_info("ah_fail_step_3") then 
			give_info("ah_fail_step_3")
			printf("Третья ошибка")
		end	
end



function kovalev_give_quest1() 
---		ah_spawn('spawn_bol_o1')
---		ah_spawn('spawn_bol_o2')
---		ah_spawn('spawn_bol_e1')
        task_manager.get_task_manager():give_task("ah_kovalev_quest1")
		task_manager.get_task_manager():give_task("ah_bol_o1_kovalev_quest1")  
		task_manager.get_task_manager():give_task("ah_bol_g1_kovalev_quest1")  
		task_manager.get_task_manager():give_task("ah_bol_e1_kovalev_quest1")	
end 


function kovalev_give_quest2()   
---		ah_spawn('spawn_agr_pda')
---		ah_spawn('spawn_agr_g1')
---		ah_spawn('spawn_agr_g2')
---		ah_spawn('spawn_agr_h1')
        task_manager.get_task_manager():give_task("ah_kovalev_quest2")
		task_manager.get_task_manager():give_task("ah_agr_pda_kovalev_quest2")		
		task_manager.get_task_manager():give_task("ah_agr_g1_kovalev_quest2")  
		task_manager.get_task_manager():give_task("ah_agr_g2_kovalev_quest2")  
		task_manager.get_task_manager():give_task("ah_agr_h1_kovalev_quest2")	
end 

function markov_give_quest1() 
---		ah_spawn('spawn_yan_o1')
---		ah_spawn('spawn_yan_h1')
---		ah_spawn('spawn_yan_h2')
        task_manager.get_task_manager():give_task("ah_markov_quest1")		
		task_manager.get_task_manager():give_task("ah_yan_o1_markov_quest1")  
		task_manager.get_task_manager():give_task("ah_yan_h1_markov_quest1")  
		task_manager.get_task_manager():give_task("ah_yan_g1_markov_quest1")		
end 

function markov_give_quest2() 
---		ah_spawn('spawn_dt_o1')
---		ah_spawn('spawn_dt_e1')
---		ah_spawn('spawn_dt_e2')
        task_manager.get_task_manager():give_task("ah_markov_quest2")		
		task_manager.get_task_manager():give_task("ah_dt_o1_markov_quest2")  
		task_manager.get_task_manager():give_task("ah_dt_e1_markov_quest2")  
		task_manager.get_task_manager():give_task("ah_dt_e2_markov_quest2")		
end 

function markov_give_quest3() 
---		ah_spawn('spawn_yan_e1')
---		ah_spawn('spawn_yan_e2')
---		ah_spawn('spawn_yan_g1')
        task_manager.get_task_manager():give_task("ah_markov_quest3")		
		task_manager.get_task_manager():give_task("ah_yan_e1_markov_quest3")  
		task_manager.get_task_manager():give_task("ah_yan_e2_markov_quest3")  
		task_manager.get_task_manager():give_task("ah_yan_g1_markov_quest3")		
end
 

function pirogov_give_quest1() 
		ah_spawn('spawn_td_o1')
---		ah_spawn('spawn_td_o2')
---		ah_spawn('spawn_td_e1')
        task_manager.get_task_manager():give_task("ah_pirogov_quest1")
		task_manager.get_task_manager():give_task("ah_td_o1_pirogov_quest1")  
		task_manager.get_task_manager():give_task("ah_td_o2_pirogov_quest1")  
		task_manager.get_task_manager():give_task("ah_td_e1_pirogov_quest1")		
end 

function pirogov_give_quest2() 
---		ah_spawn('spawn_kt_g1')
---		ah_spawn('spawn_kt_o1')
---		ah_spawn('spawn_kt_h1')
        task_manager.get_task_manager():give_task("ah_pirogov_quest2")
		task_manager.get_task_manager():give_task("ah_kt_g1_pirogov_quest2")  
		task_manager.get_task_manager():give_task("ah_kt_o1_pirogov_quest2")  
		task_manager.get_task_manager():give_task("ah_kt_h1_pirogov_quest2")		
end 

function pirogov_give_quest3() 
---		ah_spawn('spawn_sv_pda')
---		ah_spawn('spawn_sv_g1')
		ah_spawn('spawn_sv_h1')
        task_manager.get_task_manager():give_task("ah_pirogov_quest3")
		task_manager.get_task_manager():give_task("ah_sv_pda_pirogov_quest3")  
		task_manager.get_task_manager():give_task("ah_sv_g1_pirogov_quest3")  
		task_manager.get_task_manager():give_task("ah_sv_h1_pirogov_quest3")		
end 

function chernov_give_quest1() 
		ah_spawn('spawn_mil_h1')
		ah_spawn('spawn_mil_g1')
		ah_spawn('spawn_mil_o1')
        task_manager.get_task_manager():give_task("ah_chernov_quest1")
		task_manager.get_task_manager():give_task("ah_mil_h1_chernov_quest1")  
		task_manager.get_task_manager():give_task("ah_mil_g1_chernov_quest1")  
		task_manager.get_task_manager():give_task("ah_mil_o1_chernov_quest1")		
end 

function chernov_give_quest3() 
---		ah_spawn('spawn_les_pda')
---		ah_spawn('spawn_les_o1')
---		ah_spawn('spawn_les_e1')
        task_manager.get_task_manager():give_task("ah_chernov_quest3")
		task_manager.get_task_manager():give_task("ah_les_pda_chernov_quest3")  
		task_manager.get_task_manager():give_task("ah_les_o1_chernov_quest3")  
		task_manager.get_task_manager():give_task("ah_les_e1_chernov_quest3")		
end 

function chernov_give_quest4() 
		ah_spawn('spawn_lim_s1')
        task_manager.get_task_manager():give_task("ah_chernov_quest4")
end 

function chernov_give_quest5() 
		ah_spawn('spawn_rad_pda')
		ah_spawn('spawn_rad_r1')
		ah_spawn('spawn_rad_r2')
		ah_spawn('spawn_rad_r3')		
        task_manager.get_task_manager():give_task("ah_chernov_quest5") 
		task_manager.get_task_manager():give_task("ah_rad_pda_chernov_quest5")  		
---		task_manager.get_task_manager():give_task("ah_rad_r1_chernov_quest5")  
---		task_manager.get_task_manager():give_task("ah_rad_r2_chernov_quest5")  
---		task_manager.get_task_manager():give_task("ah_rad_r3_chernov_quest5")  
end 

function chernov_give_quest6() 
---		ah_spawn('spawn_mg_o1')
---		ah_spawn('spawn_mg_g1')
        task_manager.get_task_manager():give_task("ah_chernov_quest6")
		task_manager.get_task_manager():give_task("ah_mg_o1_chernov_quest6")  
		task_manager.get_task_manager():give_task("ah_mg_g1_chernov_quest6")  
end 

function juk_give_quest1() 
		ah_spawn('spawn_up_g1')
		ah_spawn('spawn_up_h1')
		ah_spawn('spawn_up_h2')
        task_manager.get_task_manager():give_task("ah_juk_quest1")
		task_manager.get_task_manager():give_task("ah_up_g1_juk_quest1")
		task_manager.get_task_manager():give_task("ah_up_h1_juk_quest1")  
		task_manager.get_task_manager():give_task("ah_up_h2_juk_quest1")		
end 

function juk_give_quest2() 
		ah_spawn('spawn_up_e1')
		ah_spawn('spawn_up_e2')
		ah_spawn('spawn_up_g2')
        task_manager.get_task_manager():give_task("ah_juk_quest2")
		task_manager.get_task_manager():give_task("ah_up_e1_juk_quest2")
		task_manager.get_task_manager():give_task("ah_up_e2_juk_quest2")  
		task_manager.get_task_manager():give_task("ah_up_g2_juk_quest2")		
end 

function juk_give_quest3() 
		ah_spawn('spawn_p_h1')
		ah_spawn('spawn_p_g1')
		ah_spawn('spawn_p_g2')
		ah_spawn('spawn_p_e1')		
        task_manager.get_task_manager():give_task("ah_juk_quest3")
		task_manager.get_task_manager():give_task("ah_p_h1_juk_quest3")
		task_manager.get_task_manager():give_task("ah_p_g1_juk_quest3")  
		task_manager.get_task_manager():give_task("ah_p_g2_juk_quest3")
		task_manager.get_task_manager():give_task("ah_p_e1_juk_quest3")		
end 



function vorobushkin_give_quest1() 
		ah_spawn('spawn_zat_pda')
		ah_spawn('spawn_zat_h1')
		ah_spawn('spawn_zat_h2')
        task_manager.get_task_manager():give_task("ah_vorobushkin_quest1")
		task_manager.get_task_manager():give_task("ah_zat_pda_vorobushkin_quest1")
		task_manager.get_task_manager():give_task("ah_zat_h1_vorobushkin_quest1")  
		task_manager.get_task_manager():give_task("ah_zat_h2_vorobushkin_quest1")		
end 

function vorobushkin_give_quest2() 
		ah_spawn('spawn_zat_g1')
		ah_spawn('spawn_zat_o1')
		ah_spawn('spawn_zat_g2')
        task_manager.get_task_manager():give_task("ah_vorobushkin_quest2")
		task_manager.get_task_manager():give_task("ah_zat_g1_vorobushkin_quest2")
		task_manager.get_task_manager():give_task("ah_zat_o1_vorobushkin_quest2")  
		task_manager.get_task_manager():give_task("ah_zat_g2_vorobushkin_quest2")		
end 

function skabinsky_give_quest1() 
---		ah_spawn('spawn_gen_f1')
        task_manager.get_task_manager():give_task("ah_skabinsky_quest1")
		task_manager.get_task_manager():give_task("ah_gen_f1_skabinsky_quest1")

end 


 
