-- Fixes to scripts via monkey patches

-- Correct behaviour of actor_on_item_before_pickup callback
function bind_stalker_ext.actor_on_item_before_pickup(item) -- called from engine!
-- Called when actor is pressing use key to pick up an item
-- return false will prevent actor from pickup the item
	local flags = { ret_value = true }
	SendScriptCallback("actor_on_item_before_pickup",item,flags)
	return flags.ret_value
end
