function init()
    exec_console_cmd("r__fakescope " .. 1)
    assert(add_scope_radii, "add_scope_radii function doesn't exist for this engine, reinstall modded exes")
    if scopeRadii and scopeRadii.scopeRadii then
        for key, val in pairs(scopeRadii.scopeRadii) do
            add_scope_radii(key, val)
        end
    end
end

-- Dummy func for heatvision compatibility
function updateScope()
    --
end

function on_game_start()
	RegisterScriptCallback( "actor_on_first_update", init )
end