function init()
    assert(add_scope_radii, "add_scope_radii function doesn't exist for this engine, reinstall modded exes")
    if render_get_dx_level() >= 655360 and scopeRadii and scopeRadii.scopeRadii then
        for key, val in pairs(scopeRadii.scopeRadii) do
            add_scope_radii(key, val)
        end
    end

end

function on_game_start()
	RegisterScriptCallback( "actor_on_first_update", init )
end