-- Additional LTX params from Modded Exes: https://github.com/themrdemonized/xray-monolith
--[[

    Objects
        ignore_collision - Objects can use "ignore_collision" in section configs to ignore collision with another objects. Can be map geometry, other physic objects, and creatures. Example: ignore_collision = map,obj,npc

    Outfits, Actor
        legs_visual - Model for first person body legs
        legs_fwd_offset - Forward position offset
    
    Weapons
        zoom_step_count - option for weapons to customize steps range for dynamic scopes. Default fallback to original 3
        scope_dynamic_zoom_gl - explicitly enable zooming with active grenade launcher
        scope_texture_alt - alternative sight crosshair
        scope_zoom_factor_alt - alternative sight zoom factor
        scope_dynamic_zoom_alt - enable adjustable scope for alt. sight
        min_scope_zoom_factor - Minimal zoom factor
        snd_shoot_actor_first - custom sound for the first shot
        snd_silncer_shoot_actor_first - custom sound for the first shot with silencer
        base_hud_offset_pos - Editable variables that allow weapon position adjustements that don't require aim tweaks
        base_hud_offset_pos_16x9 - Editable variables that allow weapon position adjustements that don't require aim tweaks
        base_hud_offset_rot - Editable variables that allow weapon position adjustements that don't require aim tweaks
        base_hud_offset_rot_16x9 - Editable variables that allow weapon position adjustements that don't require aim tweaks
        silenced_tracers - Option to disable silencers hiding the tracer on a per weapon basis
        fire_point_silencer - Adjust fire point when silencer is attached, defaults to the value of fire_point. Supports both HUD and world models
		nearwall_zoomed_range - Maximum offset toward camera when aiming down sight close to a wall.
        firepos - Disables g_firepos / g_firepos_zoom for this weapon if set to false.
        aimpos - Disables g_aimpos / g_aimpos_zoom for this weapon if set to false.
        ai_rpm - Set RPM of weapon for AI (only for SSRS)
        modular_attachments - enable modular attachments (https://github.com/themrdemonized/xray-monolith/pull/135)
        modular_scope_group - section which is used to define available scopes (modular attachments)
        inv_scope_x - ui x offset for weapon scope mount (modular attachments)
        inv_scope_y - ui y offset for weapon scope mount (modular attachments)
        attach_base_hud_offset_pos - base aim offset (modular attachments)
        attach_base_hud_offset_rot - base aim rotation (modular attachments)
        attach_mount_hud_offset_pos - scope mount offset (modular_attachments)
        attach_mount_hud_offset_rot - scope mount rotation (modular_attachments)
        attach_scale - scale modifier for all attachments (modular_attachments)

    Grenades
        frags_ap - AP power for shrapnel
        frags_air_resistance - Air resistance for shrapnel
        frags_tracer - Tracer flag for shrapnel
        frags_4to1_tracer - 4 to 1 tracer flag for shrapnel
        frags_magnetic_beam_shot - Magnetic beam flag for shrapnel
        frags_tracer_color_ID - Tracer color ID for shrapnel
        ammo_grenade_vel - Specify velocity of underbarrel grenade launcher ammo
        explode_effector_sect_name - customizable explode_effector per grenade section
        explode_on_contact - explode on contact
        on_grenade_explode - lua callback

    Explosives
        on_explode - on explode lua callback
	
	PDAs
		nearwall_zoomed_range - Maximum offset toward camera when held up close to a wall.

    Ammo
        tracer_silenced - Silencers can hide bullet tracers on a per ammo type basis
        tracer_length_k - Tracer length modifier

    Detectors
        detector_ui_bone - specifying a custom UI bone for Svarog/Veles in the hud sections of detectors
        lh_lead_gun - Device/Detector animations can now use the lead_gun bone if their hud section has lh_lead_gun = true (script animations can also use this config toggle in their section)

    Flashlight definitions
        hud_mode - toggles hud_mode for lighting, may result in different lighting and shadows

    Anomalies
        blowout_disable_idle - Setting option to true (false by default) in a config will make anomaly temporarily turn off idle particles when anomaly's blowout is triggered, particles are returned upon return to idle state.
        tele_type - New optional telekinesis type for gravitational anomalies behavior
        tele_height_fixed - (default true). If false telekinesis of gravity anomalies will not hard-stop objects at the peak point (tele_height) - they would fluctuate around it instead.
        tele_time
        tele_rotate_speed

    Particles (.pe files)
        update_step - particle update delta in milliseconds

	WeaponStatMgun
		snd_shoot: (string) Firing sound.
		snd_empty: (string) Firing sound when out of ammo.
		snd_reload: (string) Sound when reload.
		zoom_factor_def: (float) Zoom scale when holding weapon idle. Zoom closer when the value is higher.
		zoom_factor_aim: (float) Zoom scale when zooming weapon. Zoom closer when the value is higher.
		reload_delay: (float) Reload duration.
		is_single_shot_wpn: (bool) Weapon is single shot.
		unlimited_ammo: (bool) Weapon has unlimited ammo.
		reload_consume: (<script>.<function>(obj)) Return true for the weapon to consume ammo in the gunner's inventory when reload.
		shot_effector: (.anm or empty string for unused) Camera firing effector.
		ammo_class: (string) ammo section useable by this weapon. Can have multiple values seperated by commas.
		ammo_mag_size: (number) Magazine size.
		rpm: Round per minute.
		fire_dispersion_base: (float) Base dispersion of the weapon. Will add up with gunner dispersion. Degree.
		fire_dispersion_owner_scale: (float) How much gunner dispersion affect the final dispersion. Will multiply with gunner dispersion. Lower value mean gunner dispersion contribute less to the final dispersion.
		shell_particles: (.pe) Discarded cartridges particle.
		flame_particles: (.pe) Firing particle.
		smoke_particles: (.pe) Firing particle.
		on_before_use: (<script>.<function>(obj,cam_pos,cam_dir,foot_pos)) Return true to accept actor using the weapon.
		net_spawn_after: (<script>.<function>(obj)) Run right after net_spawn. Allow overriding configurations done in net_spawn.
		on_range_fov: (<script>.<function>(obj,npc,var)) Allow changing gunner visibility range while using machine gun by changing var.range. This function must return "var".
		
		barrels: (string) The weapon can have multiple barrels. This is the barrel sections in userdata file of the weapon visual model. Can have multiple values seperated by commas.
		rpm_range: (min_rpm,max_rpm) Only for weapon with multiple barrels. Each barrel will have a random rpm in this range to create asymmetric firing effect. Use "rpm" if this not exist.
		<barrel_section>@shell_particles: (.pe) Discarded cartridges particle for <barrel_section>. Use "shell_particles" if not exist.
		<barrel_section>@flame_particles: (.pe) Firing particle for <barrel_section>. Use "flame_particles" if not exist.
		<barrel_section>@smoke_particles: (.pe) Firing particle for <barrel_section>. Use "smoke_particles" if not exist.
		
		
		userdata of the weapon visual model:
			[mounted_weapon_definition]
			rotate_x_bone: (bone) Bone for vertical rotation.
			rotate_y_bone: (bone) Bone for horizontal rotation.
			rotate_x_speed: (float) Vertical rotation speed. degree/s.
			rotate_y_speed: (float) Horizontal rotation speed. degree/s.
			fire_bone: (bone) Bone where bullets come out.
			drop_bone: (bone) Bone where discarded cartridges particle plays.
			actor_bone: (bone) Bone to attach gunner.
			camera_bone_def: (bone) Bone to attach camera when idle.
			camera_bone_aim: (bone) Bone to attach camera when zoom.
			camera_position: (vector) Relative position to attach camera when using third person camera.
			exit_position: (vector) Relative position to set gunner at when they exits.
			bullet_bones: (bone) Bullet bones to set the visible bullets matching the remaining ammo. Can have multiple values seperated by commas.
			
			[animation]
			idle_body: (string) Gunner idle body animation.
			idle_legs: (string) Gunner idle legs animation.
			
			[animation_hand]
			hand_bid: (bone) Bone to attach hand model.
			hand_pos: (vector) Hand model offset for minor adjustments.
			hand_idle: (string) Hand idle animation.
			
			[camera]
			cam_first: (string) First person camera section. In system.ltx
			cam_chase: (string) Third person camera section. In system.ltx
			
			[sounds]
			volume: (float) Volume.
			rotate_snd: (.ogg) Rotating sound.
			rotate_bid: (bone) Bone where the sound plays.
			rotating_x: (bool) Play sound when rotating vertically.
			rotating_y: (bool) Play sound when rotating horizontally.
			
			[<barrel_section>]
			fire_bone: (bone) Bone where bullets come out.
			drop_bone: (bone) Bone where discarded cartridges particle plays.
	
	Projector
		net_spawn_after: (<script>.<function>(obj)) Run right after net_spawn. Allow overriding configurations done in net_spawn.
		
		userdata of the weapon visual model:
			[projector_definition]
			lights: (string) light sections in this file. Can have multiple values seperated by commas.
			controls: (string) control sections in this file. Can have multiple values seperated by commas.
			
			[<light_section>]
			range: (float) Max range.
			color: (vector 4 float RGBA) Color.
			color_animator: (string) Color animator.
			spot_angle: (float) Spot light angle. degree.
			spot_texture: (string) Spot light texture.
			glow_radius: (float) Glow radius.
			glow_texture: (string) Glow texture.
			light_bone: (bone) Bone to attach the light object.
			guide_bone: (bone) Projector bone. Hide when the light is turned off.
			
			[<control_section>]
			rotate_x_bone: (bone) Bone for vertical rotation.
			rotate_y_bone: (bone) Bone for horizontal rotation.
			rotate_x_speed: (float) Vertical rotation speed. degree/s.
			rotate_y_speed: (float) Horizontal rotation speed. degree/s.
--]]