
-- Import smart constructors
options_builder.import_into(this)

PAGE = page {
	{ id = "sound_delay" },
	track {
		id = "snd_distance_based_delay_power",
		def = 1.0,
		step = 0.1,
	},
	track {
		id = "snd_distance_based_delay_min_distance",
		def = 30,
		step = 1,
	},
	track {
		id = "snd_pitch_variation_power",
		def = 0,
		step = 0.1,
	},
	track {
		id = "snd_efx_environment_change_time",
		def = 1.66,
		step = 0.1,
	},
}