--- Aim options tree

-- Import smart constructors
options_builder.import_into(this)

-- Shader scopes
PAGE = page {
	{ id = "aim" },
	list_bool { id = "aimmode_remember"	},
	list_bool { id = "allow_outfit_control_inertion_factor" },
	list_bool { id = "allow_weapon_control_inertion_factor" },
	list_bool { id = "fix_avelocity_spread" },
	list_bool { id = "apply_pdm_to_ads" },
	list_bool { id = "smooth_ads_transition" }
}