--- Particles options tree

-- Import smart constructors
options_builder.import_into(this)

PAGE = page {
	{ id = "graphics" },
	vector {
		id = "ssfx_grass_shadows",
		x_min = 0,
		x_max = 3,
		x_def = 1,
		x_step = 1,
		y_min = 0,
		y_max = 1,
		y_step = 0.05,
		y_def = 0.35,
		z_min = 0,
		z_max = 100,
		z_step = 5,
		z_def = 30,
		w_min = 0,
		w_max = 100,
		w_step = 5,
		w_def = 0,
		path = "visual/graphics"
	},
}