--- Optimizations options tree

-- Import smart constructors
options_builder.import_into(this)

PAGE = filter_false(page {
	{ id = "optimizations" },
	list_bool { id = "spawn_antifreeze" },
	get_item_if_exists(track {
		id = "g_enemy_manager_useful_cache_time",
		def = 250,
		step = 10,
	}),

	line{},

	get_item_if_exists(check { id = "r2_mt", def = true }),
	get_item_if_exists(check { id = "mt_bullets", def = true }),
	get_item_if_exists(check { id = "mt_particles", def = true }),
	get_item_if_exists(list_bool { id = "mt_scheduler" }),
	get_item_if_exists(track {
		id = "scheduler_batch_size",
		def = 128,
		step = 4,
	}),
	get_item_if_exists(list_bool { id = "mt_calc_bones"}),
	get_item_if_exists(list_bool { id = "mt_task_manager"}),
	get_item_if_exists(list_bool { id = "mt_ui"}),
	list_bool { id = "mt_update_weapon_sounds" },
	list_bool { id = "r__optimize_torch" },

	line{},

	get_item_if_exists(list_bool { id = "mt_level_call" }),
	get_item_if_exists(list_bool { id = "lua_use_functor_cache" }),
	track {
		id = "lua_gcstep",
		def = 400,
		step = 10,
	},
	get_item_if_exists(list_bool { id = "lua_parallel_gc"}),
	get_item_if_exists(track {
		id = "lua_parallel_gcstep",
		def = 75,
		step = 5,
	}),
	get_item_if_exists(track {
		id = "lua_parallel_gc_call_amount",
		def = 25,
		step = 1,
	}),
	get_item_if_exists(list_bool { id = "lua_parallel_gc_debug" }),

	line{},

	list_bool { id = "dltx_use_cache" },
	track {
		id = "mouse_buffer_size",
		def = 1024,
		step = 32,
	},
	track {
		id = "keyboard_buffer_size",
		def = 128,
		step = 32,
	},
})