--- Control options tree

local page_keyboard = options_modded_exes_keyboard.PAGE
local page_mouse = options_modded_exes_mouse.PAGE
local page_camera = options_modded_exes_camera.PAGE
local page_pda = options_modded_exes_pda.PAGE

-- Import smart constructors
options_builder.import_into(this)

-- Options group
GROUP = group {
	{ id = "control" },
	page_keyboard,
	page_mouse,
	page_camera,
	page_pda,
}