--- Particles options tree

-- Import smart constructors
options_builder.import_into(this)

PAGE = filter_false(page {
	{ id = "graphics" },
	get_item_if_exists(track {
		id = "g_wallmark_range_static",
		def = 100,
		step = 10,
	}),
	get_item_if_exists(track {
		id = "g_wallmark_range_skeleton",
		def = 50,
		step = 10,
	}),
	get_item_if_exists(list_bool { id = "r_wallmarks_static" }),
	get_item_if_exists(list_bool { id = "r_wallmarks_dynamic" }),
	get_item_if_exists(list_bool { id = "r__blood_decals_on_objects" }),
	get_item_if_exists(track {
		id = "r_wallmarks_ssa_k",
		def = 0.5,
		step = 0.05,
	}),

	line {},

	get_item_if_exists(track {
		id = "r__rain_exp",
		def = 2,
		step = 0.1,
	}),
	get_item_if_exists(track {
		id = "r__rain_k",
		def = 99,
		step = 10,
	}),

	line {},

	get_item_if_exists(track {
		id = "r__ssa_discard",
		def = 10,
		step = 1,
	}),
	get_item_if_exists(track {
		id = "r__ssa_discard_exp",
		def = 1,
		step = 0.1,
	}),
	get_item_if_exists(track {
		id = "r__ssa_discard_fade_k",
		def = 4,
		step = 0.1,
	}),

	line {},

	list_bool { id = "r__actor_shadow_in_demo_record"},
	list_bool { id = "g_use_non_linear_inertia"},
	get_item_if_exists(list_bool { id = "pfx_volumetric_mode"}),

	line {},

	vector {
		id = "ssfx_grass_shadows",
		x_min = 0,
		x_max = 3,
		x_def = 1,
		x_step = 1,
		y_min = 0,
		y_max = 1,
		y_step = 0.05,
		y_def = 0.35,
		z_min = 0,
		z_max = 100,
		z_step = 5,
		z_def = 30,
		w_min = 0,
		w_max = 100,
		w_step = 5,
		w_def = 0,
		path = "visual/graphics"
	},
})