--- Optimizations options tree

-- Import smart constructors
options_builder.import_into(this)

PAGE = filter_false(page {
	{ id = "optimizations" },
	list_bool { id = "spawn_antifreeze" },
	get_item_if_exists(track {
		id = "g_enemy_manager_useful_cache_time",
		def = 250,
		step = 10,
	}),

	line{},

	get_item_if_exists(check { id = "r2_mt", def = true }),
	get_item_if_exists(check { id = "mt_bullets", def = true }),
	get_item_if_exists(check { id = "mt_particles", def = true }),
	get_item_if_exists(list_bool { id = "mt_scheduler" }),
	get_item_if_exists(track {
		id = "scheduler_batch_size",
		def = 256,
		step = 64,
	}),
	get_item_if_exists(list_bool { id = "mt_calc_bones"}),
	list_bool { id = "mt_update_weapon_sounds" },
	get_item_if_exists(list_bool { id = "r__optimize_torch" }),
	get_item_if_exists(list_bool { id = "r2_shadow_omnipart_vischeck" }),

	line{},

	get_item_if_exists(list_bool { id = "lua_use_functor_cache" }),
	track {
		id = "lua_gcstep",
		def = 400,
		step = 10,
	},
	list_bool { id = "lua_parallel_gc"},
	track {
		id = "lua_parallel_gcstep",
		def = 75,
		step = 5,
	},
	track {
		id = "lua_parallel_gc_call_amount",
		def = 25,
		step = 1,
	},
	list_bool { id = "lua_parallel_gc_debug" },

	line{},

	get_item_if_exists(list_bool { id = "r__clear_resources_on_unload" }),
	get_item_if_exists(list_bool { id = "r__tex_evict_enabled" }),
	get_item_if_exists(track {
		id = "r__tex_evict_age_frames",
		def = 1024,
		step = 32,
	}),
	get_item_if_exists(track {
		id = "r__tex_evict_batch_size",
		def = 1024,
		step = 32,
	}),
	list_bool { id = "dltx_use_cache" },
	track {
		id = "mouse_buffer_size",
		def = 1024,
		step = 32,
	},
	track {
		id = "keyboard_buffer_size",
		def = 128,
		step = 32,
	},

	line{},

	desc {
		id= "title",
		text= "ui_mm_modded_exes_optimizations_unstable_text",
		align= "l",
		clr= {255,255,255,255}
	},
	get_item_if_exists(list_bool { id = "mt_schedulerRT" }),
	get_item_if_exists(list_bool { id = "mt_level_call" }),
	get_item_if_exists(list_bool { id = "mt_task_manager"}),
	get_item_if_exists(list_bool { id = "mt_ui"}),
	get_item_if_exists(check { id = "r__hom_dynamic" }),
})