--- Launchers options tree

-- Import smart constructors
options_builder.import_into(this)

PAGE = page {
	{ id = "weapons" },
	list_bool { id = "g_auto_reload" },
	-- list_bool { id = "g_fire_reloads_ubgl" },
	-- list_bool { id = "g_launcher_dynamic_range" },
	-- list_bool { id = "g_launcher_dynamic_range_zoom" },
	-- list_bool { id = "g_launcher_dynamic_range_mode" },
	-- track {
	-- 	id = "g_launcher_dynamic_range_max",
	-- 	def = 300,
	-- 	step = 1,
	-- },
}