function on_mcm_load()
	options = {
		id = "more_measurement_task_maps", 
		sh = true,
		gr = {
            { id = "title", type = "slide", link = "ui_options_slider_radio", text = "ui_mcm_more_measurement_task_maps_title", size = {512,50}, spacing= 20 },
			{ id = "title_desc", type = "desc", text = "ui_mcm_more_measurement_task_maps_title_desc" },

			{ id = "override_eligible_map_distances_parameter",	type = "check", val = 1, def = true },
			{ id = "eligible_map_distances_parameter",			type = "list", val = 0, def = 5, content = {
					{1, "more_measurement_task_maps_same_level_label"},
					{2, "more_measurement_task_maps_same_or_nearby_levels_label"},
					{3, "more_measurement_task_maps_nearby_levels_only_label"},
					{4, "more_measurement_task_maps_far_levels_label"},
					{5, "more_measurement_task_maps_all_levels_label"},
				}
			},
			{ id = "allow_more_southern_maps",					type = "check", val = 1, def = true },
			{ id = "allow_more_northern_maps",					type = "check", val = 1, def = false },
			{ id = "allow_very_northern_maps",					type = "check", val = 1, def = false },
			{ id = "allow_underground_maps",					type = "check", val = 1, def = false },
		}
	}

	return options
end