local old_delay_event_timer = utils_item.delay_event_timer
utils_item.delay_event_timer = function(to_create, to_release, news)
    if to_release == nil or #to_release == 0 then
        return old_delay_event_timer(to_create, to_release, news)
    end

    for i=1,#to_release do
        if not (not to_release[i] or to_release[i] and level.object_by_id(to_release[i])) then
            return true
        end
    end

    return old_delay_event_timer(to_create, to_release, news)
end