custom_bone_value	= {} -- this a table with each identifier being npcid_boneid, these returns custom bonearmor value. It is filled, alongside the other custom tables, after every new bone hit
custom_bone_ap	= {} 
custom_bone_hf	= {} 
custom_bone_dmg	= {}
invincible_npcs_ids = {}
ini_capture	 = ini_file("creatures\\grok_bo_models_capture.ltx")
ini_bones		 = ini_file("creatures\\grok_bo_bone_profiles.ltx")
ini_damage		= ini_file("creatures\\damages.ltx")

leg_meta_sniper_null = 1
sniper_bad_bone_shit_reduce = 1


integrated_silencer = {
	["wpn_dvl10_m1"] = true,
	["wpn_vssk"] = true,
	["wpn_val_tac"] = true,
	["wpn_vintorez"] = true,
	["wpn_val"] = true,
	["wpn_val_modern"] = true,
	["wpn_vintorez_m1"] = true,
	["wpn_vintorez_m2"] = true,
	["wpn_vintorez_isg"] = true,
	["wpn_mp5sd"] = true,
	["wpn_mp5sd_custom"] = true,
	["wpn_mp5sd_new"] = true,
}

local difficulty_multiplier = {
	[1]  = 1.3,
	[2]  = 1.05,
	[3]  = 0.90,
	[4]  = 0.80,
}

Bone_IDs = {
[2]  =	"bip01_pelvis",
[3]  =	"bip01_l_thigh",
[4]  =	"bip01_l_calf",
[5]  =	"bip01_l_foot",
[7]  =	"bip01_r_thigh",
[8]  =	"bip01_r_calf",
[9]  =	"bip01_r_foot",
[11] =	"bip01_spine",
[12] =	"bip01_spine1",
[13] =	"bip01_spine2",
[14] =	"bip01_neck",
[15] =	"bip01_head",
[16] =	"eye_left",
[17] =	"eye_right",
[18] =	"eyelid_1",
[19] =	"jaw_1",
[20] =	"bip01_l_clavicle",
[21] =	"bip01_l_upperarm",
[22] =	"bip01_l_forearm",
[23] =	"bip01_l_forearm",
[33] =	"bip01_r_clavicle",
[34] =	"bip01_r_upperarm",
[35] =	"bip01_r_forearm",
[36] =	"bip01_r_forearm",
}

local headBones = {
	[14] = true,
	[15] = true,
	[16] = true,
	[17] = true,
	[18] = true,
	[19] = true
}

local head_bones = {
    [14] =	"bip01_neck", 
    [15] =	"bip01_head",
    [16] =	"eye_left",
    [17] =	"eye_right",
    [18] =	"eyelid_1",
    [19] =	"jaw_1",
}

local upper_body_group = {
	[11] =	"bip01_spine",
	[12] =	"bip01_spine1",
	[13] =	"bip01_spine2",
	[20] =	"bip01_l_clavicle",
	[21] =	"bip01_l_upperarm",
	[22] =	"bip01_l_forearm",
	[23] =	"bip01_l_forearm",
	[33] =	"bip01_r_clavicle",
	[34] =	"bip01_r_upperarm",
	[35] =	"bip01_r_forearm",
	[36] =	"bip01_r_forearm",
}

local lower_body_group = {
	[2]  =	"bip01_pelvis",
	[3]  =	"bip01_l_thigh",
	[4]  =	"bip01_l_calf",
	[5]  =	"bip01_l_foot",
	[7]  =	"bip01_r_thigh",
	[8]  =	"bip01_r_calf",
	[9]  =	"bip01_r_foot",
}


stalker_damage = {
default						= 0.75,

bip01_pelvis 				= 0.9,
bip01_spine 		 		= 0.9,
bip01_spine1 		 		= 0.9,
bip01_spine2 		 		= 0.9,
bip01_neck 			 		= 2.70,
bip01_head 			 		= 3.65, 
eyelid_1 			 		= 3.65, 
eye_left 			 		= 3.65, 
eye_right 			 		= 3.65, 
jaw_1 		 		 		= 3.00,

bip01_l_clavicle	 		= 0.7,
bip01_l_upperarm	 		= 0.7, 
bip01_l_forearm	 	 		= 0.6,
bip01_l_hand	 	 		= 0.4,
bip01_l_finger0	 	 		= 0.4,
bip01_l_finger01	 		= 0.4,
bip01_l_finger02	 		= 0.4,
bip01_l_finger1	 	 		= 0.4,
bip01_l_finger11	 		= 0.4,
bip01_l_finger12	 		= 0.4,
bip01_l_finger2	 	 		= 0.4,
bip01_l_finger21	 		= 0.4,
bip01_l_finger22	 		= 0.4,
bip01_r_clavicle	 		= 0.7,
bip01_r_upperarm	 		= 0.7, 
bip01_r_forearm	 	 		= 0.6,
bip01_r_hand	 	 		= 0.4,
bip01_r_finger0	 	 		= 0.4,
bip01_r_finger01	 		= 0.4, 
bip01_r_finger02	 		= 0.4,
bip01_r_finger1	 	 		= 0.4,
bip01_r_finger11	 		= 0.5,
bip01_r_finger12	 		= 0.4,
bip01_r_finger2	 	 	 	= 0.4,
bip01_r_finger21	 		= 0.4,
bip01_r_finger22	 		= 0.4,
bip01_l_thigh	 	 		= 0.55,
bip01_l_calf	 	 		= 0.45,
bip01_l_foot	 	 		= 0.3,
bip01_l_toe0	 	 		= 0.3,
bip01_r_thigh	 	 		= 0.55,
bip01_r_calf	 	 		= 0.45,
bip01_r_foot	 	 		= 0.3,
bip01_r_toe0	 	 		= 0.3,
}

hp_rounds = {
	["ammo_357_hp_mag"] = 2,
	["ammo_357_hp_mag_bad"] = 2,
	["ammo_357_hp_mag_verybad"] = 2,
	["ammo_9x18_pmm"] = 2,
	["ammo_9x18_pmm_bad"] = 2,
	["ammo_9x18_pmm_verybad"] = 2,
	["ammo_9x19_pbp"] = 2,
	["ammo_9x19_pbp_bad"] = 2,
	["ammo_9x19_pbp_verybad"] = 2,
	["ammo_7.62x25_p"] = 1.75,
	["ammo_7.62x25_p_bad"] = 1.75,
	["ammo_7.62x25_p_verybad"] = 1.75,
	["ammo_11.43x23_hydro"] = 2.7,
	["ammo_11.43x23_hydro_bad"] = 2.7,
	["ammo_11.43x23_hydro_verybad"] = 2.7,
	["ammo_5.45x39_ep"] = 1.45,
	["ammo_5.45x39_ep_bad"] = 1.45,
	["ammo_5.45x39_ep_verybad"] = 1.45,
	["ammo_5.56x45_ss190"] = 1.33,
	["ammo_5.56x45_ss190_bad"] = 1.33,
	["ammo_5.56x45_ss190_verybad"] = 1.33,
	["ammo_12x76_zhekan"] = 3.5,
	["ammo_12x76_zhekan_bad"] = 3.5,
	["ammo_12x76_zhekan_verybad"] = 3.5,
	["ammo_12x76_dart"] = 1.5,
	["ammo_12x76_dart_bad"] = 1.5,
	["ammo_12x76_dart_verybad"] = 1.5,
	["ammo_12x70_buck"] = 3,
	["ammo_12x70_buck_bad"] = 3,
	["ammo_12x70_buck_verybad"] = 3,
	["ammo_23x75_shrapnel"] = 2,
	["ammo_23x75_barrikada"] = 3.5,
	["ammo_20x70_buck"] = 2,
}

function perk_based_artefacts.npc_on_before_hit(npc, shit, bone_id, flags) end
function perk_based_artefacts.npc_on_hit_callback(npc, amount, local_direction, who, bone_index) end
function perk_based_artefacts.npc_on_death_callback(npc, who) end

local pba = perk_based_artefacts

function PBA_obh(npc, shit, bone_id, flags)
	pba.last_npc_hit = hit(shit)
	pba.last_npc_hit_bone_index = bone_id
	perk_based_artefacts.process_artefacts(perk_based_artefacts.artefact_on_npc_before_hit_functions, npc, shit, bone_id, flags)
end

function PBA_ohc(npc, amount, local_direction, who, bone_index)
	perk_based_artefacts.process_artefacts(perk_based_artefacts.artefact_on_npc_hit_functions, npc, amount, local_direction, who, bone_index, pba.last_npc_hit)
end

function PBA_odc(npc, who)
	perk_based_artefacts.process_artefacts(perk_based_artefacts.artefact_on_npc_death_functions, npc, who, pba.last_npc_hit, pba.last_npc_hit_bone_index)
end

function monster_on_before_hit(monster,shit,bone_id)

	if shit.draftsman:id() ~= db.actor:id() then
		return
	end

	if bone_id == 65535 then
		return
	end

	if shit.power >= 50 then
		return
	end

	local shooter = shit.draftsman
	wpn = level.object_by_id(shit.weapon_id)

	if wpn == nil then 
		return 
	end

	if IsGrenade(wpn) then
		return
	end

	sec = wpn:section()

	if sec == "explosive_barrel" or sec == "explosive_barrel_low" or sec == "explosive_tank" or sec == "explosive_grenade" or sec == "explosive_hide" or sec == "explosive_particle" or sec == "explosive_fuelcan" 
	or sec == "explosive_mobiltank" or sec == "explosive_dinamit" then
		return
	end
	
	cqc_mult = 1
	mutant_mult		= 0.85
	ammo_mult		= 0.85
	spec_monster_mult	= 1.00
	bone_mult		= 1.00

	printf("///////////   Mutant Hit registered: GBO v1.6.6   //////////////////")
	printf('%s about to be hit by %s in bone %s', monster and monster:name(), shit and shit.draftsman and shit.draftsman:name(), bone_id)

	if (string.match(sec, "knife")) then
		cqc_mult = 1.50
		printf('Close quarter combat hit detected')
	end

	if (string.match(sec, "axe")) then
		cqc_mult = 1.50
		printf('Close quarter combat hit detected')
	end

	local wpn_id = wpn:id()
	local ammo_type_number = wpn:get_ammo_type()
	local ammo_list = utils_item.get_ammo(sec, wpn_id)
	local ammo_section = ammo_list[ammo_type_number+1]
	local wpn_hit_power = ui_wpn_params.read_float(sec, "", "hit_power")

	if string.find(sec, "wpn_toz106") then
		wpn_hit_power = 0.8
	end
	
	if not ammo_section then
		return
	end

	-- /// save ammo data ///
	local k_ap = ini_sys:r_float_ex(ammo_section, "k_ap") * 10 or 0
	local k_hit = ini_sys:r_float_ex(ammo_section, "k_hit") or 1
	local air_res = ini_sys:r_float_ex(ammo_section, "k_air_resistance") or 0.05
	local monster_pos = monster:position()
	local shooter_pos = shooter:position()
	local dist = monster_pos:distance_to(shooter_pos)

	if ammo_section == "ammo_12x70_buck" or ammo_section == "ammo_12x70_buck_bad" or 
	   ammo_section == "ammo_20x70_buck" then
		ammo_mult = 0.90
	end
	
	if ammo_section == "ammo_23x75_shrapnel" then
		ammo_mult = 1.00
	end

	if ammo_section == "ammo_12x76_zhekan" or ammo_section == "ammo_12x76_zhekan_bad" then
		ammo_mult = 1.00
	end

	if ammo_section == "ammo_23x75_barrikada" then
		ammo_mult = 1.00
	end

	if ammo_section == "ammo_9x19_pbp" or ammo_section == "ammo_9x19_pbp_bad" 
	or ammo_section == "ammo_9x18_pmm" or ammo_section == "ammo_9x18_pmm_bad" 
	or ammo_section == "ammo_5.45x39_ep" or ammo_section == "ammo_5.45x39_ep_bad" 
	or ammo_section == "ammo_5.56x45_ss190" or ammo_section == "ammo_5.56x45_ss190_bad"  then
		ammo_mult = 1.00
	end

	if ammo_section == "ammo_7.62x25_ps"  or ammo_section == "ammo_7.62x25_ps_bad" then
		ammo_mult = 1.00
	end

	if ammo_section == "ammo_7.62x25_p"  or ammo_section == "ammo_7.62x25_p_bad" then
		ammo_mult = 1.75
	end

	if ammo_section == "ammo_357_hp_mag" or ammo_section == "ammo_357_hp_mag_bad" then
		ammo_mult = 1.00
	end

 	if ammo_section == "ammo_11.43x23_hydro"  or ammo_section == "ammo_11.43x23_hydro_bad"  then
		ammo_mult = 1.00
	end

 	if ammo_section == "ammo_11.43x23_fmj"  or ammo_section == "ammo_11.43x23_fmj_bad"  then
		ammo_mult = 1.00
	end

	-- /// save gun barrel data ///
	if (IsWeapon(wpn) and (not IsItem("fake_ammo_wpn",wpn:section()))) or (wpn:parent() and wpn:parent():id() ~= 0) then
		barrel_condition = nil
		local parts = se_load_var(wpn:id(), wpn:name(), "parts")
		if parts ~= nil then
			for k,v in pairs(parts) do
				if string.find(k, "barrel") then
					barrel_condition = v / 100
				end
			end

			if barrel_condition == nil then
				barrel_condition = 1
			end
		else
			barrel_condition = 1
		end

		barrel_condition_corrected = ( 130 - ( 1.12 * barrel_condition ) ) * ( barrel_condition * 1.12 ) / 100

		if barrel_condition_corrected > 1 then
			barrel_condition_corrected = 1
		end
	else
		barrel_condition = 1
		barrel_condition_corrected = 1
	end

	-- /// mutants body parts multipliers ///
	if string.find(monster:name(), "gigant") then
	
		spec_monster_mult = 0.85
		
		if ammo_section == "ammo_12x70_buck" or ammo_section == "ammo_12x70_buck_bad" or 
	    ammo_section == "ammo_20x70_buck" then
			ammo_mult = 1.4
		end

		if ammo_section == "ammo_23x75_shrapnel" then
			ammo_mult = 2.2
		end
		
		if ammo_section == "ammo_23x75_barrikada" then
			ammo_mult = 2.3
		end
		
		if ammo_section == "ammo_357_hp_mag" or ammo_section == "ammo_357_hp_mag_bad" then
			ammo_mult = 1.3
		end
		
		if ammo_section == "ammo_11.43x23_hydro"  or ammo_section == "ammo_11.43x23_hydro_bad"  then
			ammo_mult = 1.3
		end

		if ammo_section == "ammo_7.62x25_p"  or ammo_section == "ammo_7.62x25_p_bad" then
			ammo_mult = 2.00
		end
		
		if (bone_id == 1) then
			bone_mult = 2.00
			printf("Critical Hit!")
		end
	end

	if string.find(monster:name(), "chimera") then
		spec_monster_mult = 0.75
		if (bone_id == 33 or bone_id == 24 or bone_id == 25 or bone_id == 23 or bone_id == 28) then
			bone_mult = 2.00
			printf("Critical Hit!")
		end
	end

	if string.find(monster:name(), "boar") then
		spec_monster_mult = 0.95
	end

	if string.find(monster:name(), "bloodsucker") then
		spec_monster_mult = 0.85
		if bone_id == 14 then
			bone_mult = 1.40
			printf("Critical Hit!")
		end
	end

	if string.find(monster:name(), "psysucker") then
		spec_monster_mult = 0.85
		if bone_id == 14 then
			bone_mult = 1.60
			printf("Critical Hit!")
		end
	end

	if string.find(monster:name(), "flesh") then
		spec_monster_mult = 0.95
		if bone_id == 13 then
			bone_mult = 1.30
		end
	end

	if string.find(monster:name(), "zombi") then
		spec_monster_mult = 0.80
		if bone_id == 12 then
			bone_mult = 2.00
			printf("Critical Hit!")
		end
	end

	if string.find(monster:name(), "snork") then
		spec_monster_mult = 1.10
		if bone_id == 4 or bone_id == 5 then
			bone_mult = 2.00
			printf("Critical Hit!")
		end
	end


	if string.find(monster:name(), "lurker") then
		spec_monster_mult = 0.85
		if bone_id == 25 or bone_id == 26 or bone_id == 28 or bone_id == 23 then
			bone_mult = 1.50
			printf("Critical Hit!")
		end
	end


	if string.find(monster:name(), "fracture") then
		spec_monster_mult = 0.60
		if (bone_id == 12 or bone_id == 13) then
			bone_mult = 2.20
			printf("Critical Hit!")
		end
	end
	
	local gameplay = alife_storage_manager.get_state().diff_game
	if not (type(gameplay) == "table") then -- for old saves
		alife_storage_manager.get_state().diff_game = {}
		alife_storage_manager.get_state().diff_game["type"] = game_num
		gameplay = alife_storage_manager.get_state().diff_game
	end

	local game_num = gameplay["type"] or game_num

	
	shit.power = shit.power / ( 1 + dist / 200 * ( air_res * 0.5 / ( 1 - air_res + 0.1 ))) * mutant_mult * ammo_mult * spec_monster_mult * bone_mult * cqc_mult * barrel_condition_corrected * difficulty_multiplier[game_num]

	printf("Barrel condition: %s, GBO output damage: %s", barrel_condition, shit.power)
	return
end




function npc_on_before_hit(npc,shit,bone_id)

	if shit.draftsman:id() ~= db.actor:id() then
		return
	end

	if bone_id == 65535 then
		return
	end

	local surrender_bonus = 0
	if shit.power >= 50 then
		surrender_bonus = 1
		printf("npc is surrendering or wounded.")
	end

	local shooter = shit.draftsman
	wpn = level.object_by_id(shit.weapon_id)
	sec = wpn:section()

	if sec == "explosive_barrel" or sec == "explosive_barrel_low" or sec == "explosive_tank" or sec == "explosive_grenade" or sec == "explosive_hide" or sec == "explosive_particle" or sec == "explosive_fuelcan" 
	or sec == "explosive_mobiltank" or sec == "explosive_dinamit" then
		return
	end

	if IsGrenade(wpn) then
		return
	end

	if wpn == nil then 
		return 
	end

	printf("///////////   Stalker Hit registered: GBO v1.6.6  //////////////////")
	printf('%s about to be hit by %s in bone %s', npc and npc:name(), shit and shit.draftsman and shit.draftsman:name(), bone_id)
	
--////////////// INVICIBILITY TRIGGER FOR ITHEON'S TASKS //////////////

	if invincible_npcs_ids[npc:id()] then
		invincible_mult = 0
	else
		invincible_mult = 1
	end

	
--////////////// DATA PARSING OF HELL - A BONES AND BOOLETS TALE //////////////

--	/////// BOOLETS //////

	local wpn_id = wpn:id()
	local ammo_type_number = wpn:get_ammo_type()
	local ammo_list = utils_item.get_ammo(sec, wpn_id)
	local ammo_section = ammo_list[ammo_type_number+1]
	local wpn_hit_power = ui_wpn_params.read_float(sec, "", "hit_power")
	if wpn and wpn:weapon_is_silencer() then
		silencer_boost = 1.07
	else
		silencer_boost = 1
	end
	
	if sec and integrated_silencer[sec] then
		silencer_boost = 1.07
	end

	if string.find(sec, "wpn_toz106") then
		wpn_hit_power = 0.8
	end
	
	if not ammo_section then
		return
	end

	-- /// save ammo data ///
	local k_ap = ini_sys:r_float_ex(ammo_section, "k_ap") * 10 or 0
	local k_hit = ini_sys:r_float_ex(ammo_section, "k_hit") or 1
	local air_res = ini_sys:r_float_ex(ammo_section, "k_air_resistance") or 0.05
	local wm_size = ini_sys:r_float_ex(ammo_section, "wm_size") or 0.05
	local npc_pos = npc:position()
	local shooter_pos = shooter:position()
	local dist = npc_pos:distance_to(shooter_pos)


	-- /// save gun barrel data ///

	if (IsWeapon(wpn) and (not IsItem("fake_ammo_wpn",wpn:section()))) or (wpn:parent() and wpn:parent():id() ~= 0) then
		barrel_condition = nil
		local parts = se_load_var(wpn:id(), wpn:name(), "parts")
		if parts ~= nil then
			for k,v in pairs(parts) do
				if string.find(k, "barrel") then
					barrel_condition = v / 100
				end
			end

			if barrel_condition == nil then
				barrel_condition = 1
			end
		else
			barrel_condition = 1
		end

		barrel_condition_corrected = ( 130 - ( 1.12 * barrel_condition ) ) * ( barrel_condition * 1.12 ) / 100

		if barrel_condition_corrected > 1 then
			barrel_condition_corrected = 1
		end
	else
		barrel_condition = 1
		barrel_condition_corrected = 1
	end

--	/////// AMMO SPECIFIC DAMAGE ADJUSTMENT //////

	ammo_mult = 1.00

	if ammo_section == "ammo_7.62x25_p"  or ammo_section == "ammo_7.62x25_p_bad" then
		ammo_mult = 1.75
	end

--	/////// AMMO SPECIFIC BONES REDIRECTION //////

-- Disables legmeta on snipers.

	if (ammo_section == "ammo_7.92x33_ap" or ammo_section == "ammo_7.92x33_ap_bad" or ammo_section == "ammo_7.92x33_fmj" or ammo_section == "ammo_7.92x33_fmj_bad" or
	ammo_section == "ammo_7.62x54_7h1" or ammo_section == "ammo_7.62x54_7h1_bad" or ammo_section == "ammo_7.62x54_ap" or ammo_section == "ammo_7.62x54_ap_bad" or
	ammo_section == "ammo_7.62x54_7h14" or ammo_section == "ammo_7.62x54_7h14_bad" or
	ammo_section == "ammo_magnum_300" or ammo_section == "ammo_magnum_300_bad" or
	ammo_section == "ammo_50_bmg" or ammo_section == "ammo_50_bmg_bad" or ammo_section == "ammo_gauss" or ammo_section == "ammo_gauss_bad" or
	sec == "wpn_l96a1" or sec == "wpn_mk14" or sec == "wpn_remington700" or sec == "wpn_m40_cw" or sec == "wpn_wa2000" ) then	
		leg_meta_sniper_null = 0
	end
	
-- HP rounds damage reduction if ammo doesn't penetrate

	if hp_rounds[ammo_section] and hp_rounds[ammo_section] > 0 then
		hp_no_penetration_penalty = hp_rounds[ammo_section]
	else
		hp_no_penetration_penalty = 1
	end
	
-- Knife and axes specific stuff

--	if (ammo_section == "ammo_knife" or   
--	    ammo_section == "ammo_knife1" or  ammo_section == "ammo_knife2" or  ammo_section == "ammo_knife3" or  ammo_section == "ammo_knife4" or  ammo_section == "ammo_knife5" or 
--	    ammo_section == "ammo_knife_1" or ammo_section == "ammo_knife_2" or ammo_section == "ammo_knife_3" or ammo_section == "ammo_knife_4" or ammo_section == "ammo_knife_5") then
--		bone_id = 12
--		printf("Knife hit, redirecting to torso")
--	end

--	/////// BONES DEFINITION //////

	local npc_id = npc:id()
	local custom_bone_name = Bone_IDs[bone_id] 
	
	if not custom_bone_name then
		custom_bone_name = math.random(52,55) 
		if custom_bone_name == 52 then
			bone_id = 22
			custom_bone_name = "bip01_l_forearm"
		elseif custom_bone_name == 53 then
			bone_id = 35
			custom_bone_name = "bip01_r_forearm"
		elseif custom_bone_name == 54 then
			bone_id = 21
			custom_bone_name = "bip01_l_upperarm"
		elseif custom_bone_name == 55 then
			bone_id = 34
			custom_bone_name = "bip01_r_upperarm"
		end
	end
	
--	/////// BONES GROUPING //////

	-- We keep actually hit bone damage multiplier

	local bone_damage_multiplier = stalker_damage[custom_bone_name]
	 
	-- We regroup bones armor in group-wise armor (one armor value for multiple bones)

	bone_ap_boost = bone_id

	if upper_body_group[bone_id] then
		bone_id = 11
	end
	
	if lower_body_group[bone_id] then
		bone_id = 2
	end
	
	if head_bones[bone_id] then
		bone_id = 15
	end
	
	local custom_bone_id = (npc_id.."_"..bone_id)
	custom_bone_dmg[custom_bone_id] = tonumber(bone_damage_multiplier)

--	/////// CUSTOM BONE CHECK AND BONE PROFILE LOADING //////

-- In case npc didn't get shot already in this bone, we store the default bone armor in the table.

	if custom_bone_value[custom_bone_id] then
		printf("Custom bone found. Loading custom_bone values")
	else



-- get bone profile

		local npc_viz = npc:get_visual_name()
		printf("NPC visual model: %s",npc_viz)

		if not ini_capture:section_exist(npc_viz) then
			printf("NPC model doesn't have a bone profile, loading berill no helm config")
			npc_viz = "actors\\stalker_bandit\\stalker_bandit_berill_nohelm_1"
			--printf(npc_viz)
		end

		local npc_armor_path = ini_capture:r_string(npc_viz,"model_path")	
		ini_npc_armor = ini_file(npc_armor_path)
		local npc_armor_section = ini_npc_armor:r_string('bone_protection','bones_protection_sect')
		if (tonumber(bone_id) >= 14 and tonumber(bone_id) <= 19) then -- headshot
			npc_bone_profile_name = ini_bones:r_string(npc_armor_section,"head_profile")
		else -- bodyshot
			npc_bone_profile_name = ini_bones:r_string(npc_armor_section,"bone_profile")
		end
		local tmp1 =	ini_damage:r_string(npc_bone_profile_name,custom_bone_name)
		local p = str_explode(tmp1,",")

-- 		/////// save bone armor value /////// 

		custom_bone_value[custom_bone_id] = tonumber(p[2])

		if npc:section() == "monolith_eidolon" then
			custom_bone_value[custom_bone_id] = 4
			-- Add a gravi shield effect to make Eidolon even more unique
			pos = npc:bone_position(custom_bone_name)
			fxdir = shit.direction
			fxdir.x = (fxdir.x * -1.0) + math.random(-0.009, 0.009)
			fxdir.y = fxdir.y + math.random(-0.0045, 0.0045)
			fxdir.z = (fxdir.z * -1.0) + math.random(-0.009, 0.009)
			camdir = device().cam_pos:add(device().cam_dir:mul(dist))
			pos.x = pos.x + (camdir.x * -0.0005)
			pos.z = pos.z + (camdir.z * -0.0005)
			fx = particles_object("anomaly2\\gravi_anomaly_shield_00")
			fx:set_direction(fxdir)
			fx:play_at_pos(pos)		
		end
	
-- 		/////// save hit_fraction value /////// 

		local npc_hit_fraction = ini_bones:r_string(npc_armor_section,"hit_fraction_npc")
		custom_bone_hf[custom_bone_id] = tonumber(npc_hit_fraction)

-- 		/////// save ap_scale value /////// 

		local npc_ap_scale = ini_bones:r_string(npc_armor_section,"ap_scale")
		custom_bone_ap[custom_bone_id] = tonumber(npc_ap_scale)
	end
	

--	/////// CHECK IF NPC IS FROM THE SIN FACTION TO REDUCE DAMAGES //////

		local se_obj = alife_object(npc:id())
		local faction = se_obj:community()
		sin_res = 1
		if faction == "greh" then
			sin_res = 0.30
			isg_res = 0.90
			pos = npc:bone_position(custom_bone_name)
			fxdir = shit.direction
			fxdir.x = (fxdir.x * -1.0) + math.random(-0.009, 0.009)
			fxdir.y = fxdir.y + math.random(-0.0045, 0.0045)
			fxdir.z = (fxdir.z * -1.0) + math.random(-0.009, 0.009)
			camdir = device().cam_pos:add(device().cam_dir:mul(dist))
			pos.x = pos.x + (camdir.x * -0.0005)
			pos.z = pos.z + (camdir.z * -0.0005)
			fx = particles_object("monsters\\effects\\bloodsucker_trail")
			fx:set_direction(fxdir)
			fx:play_at_pos(pos)
			fx = particles_object("monsters\\effects\\polter_trails_02")
			fx:set_direction(fxdir)
			fx:play_at_pos(pos)			
			fx = particles_object("anomaly2\\effects\\bloodsucker_shleyf")
			fx:set_direction(fxdir)
			fx:play_at_pos(pos)			
		end
		
--	/////// CHECK IF NPC IS FROM THE ISG FACTION TO REDUCE PENETRATION AND DAMAGE //////

		isg_res = 1
		if faction == "isg" then
			isg_res = 0.65
			sin_res = 0.70
			pos = npc:bone_position(custom_bone_name)
			fx = particles_object("hit_fx\\hit_metal_0" .. math.random(0,3))
			fxdir = shit.direction
			fxdir.x = (fxdir.x * -1.0) + math.random(-0.009, 0.009)
			fxdir.y = fxdir.y + math.random(-0.0045, 0.0045)
			fxdir.z = (fxdir.z * -1.0) + math.random(-0.009, 0.009)
			fx:set_direction(fxdir)
			camdir = device().cam_pos:add(device().cam_dir:mul(dist))
			pos.x = pos.x + (camdir.x * -0.0005)
			pos.z = pos.z + (camdir.z * -0.0005)
			fx:play_at_pos(pos)
		end
		
		if faction == "monolith" then
			isg_res = 0.90
			sin_res = 0.80
		end
		
		if faction == "bandit" then
			isg_res = 1.10
		end

--////////////// ACTUAL INTERESTING MATH PART ABOUT BALLISTICS //////////////
	
	local gameplay = alife_storage_manager.get_state().diff_game
	if not (type(gameplay) == "table") then -- for old saves
		alife_storage_manager.get_state().diff_game = {}
		alife_storage_manager.get_state().diff_game["type"] = game_num
		gameplay = alife_storage_manager.get_state().diff_game
	end

	local game_num = gameplay["type"] or game_num

	--printf("// Ammo data :")
	--printf('game_num = %s', game_num)
	printf('%s shot with %s, Weapon power= %s, AP power= %s, Hit multiplier= %s, Air res= %s, Distance= %s m, Barrel condition: %s', ammo_section, sec, wpn_hit_power, k_ap, k_hit, air_res, dist, barrel_condition)
	printf('Bone hit= %s, Bone damage mult= %s, Bone AP scale= %s, Bone hit fraction= %s, Bone armor= %s', custom_bone_name, custom_bone_dmg[custom_bone_id], custom_bone_ap[custom_bone_id], custom_bone_hf[custom_bone_id], custom_bone_value[custom_bone_id])

	local custom_bone_armor = custom_bone_value[custom_bone_id]
	local custom_bone_dmg_mult = custom_bone_dmg[custom_bone_id]
	local custom_bone_ap_scale = custom_bone_ap[custom_bone_id]
	local custom_bone_hitfraction = custom_bone_hf[custom_bone_id]

	if tonumber(bone_ap_boost) >= 3 and tonumber(bone_id) <= 9 then -- leg meta, bullets ap boost in legs
		if ammo_section == "ammo_12x70_buck" or ammo_section == "ammo_12x70_buck_bad" or
		   ammo_section == "ammo_20x70_buck" or ammo_section == "ammo_23x75_shrapnel" then
			k_ap = ( k_ap + 0.013 )
		else
			k_ap = ( k_ap + (0.075 * leg_meta_sniper_null) )
		end
	end

	if tonumber(bone_ap_boost) >= 16 and tonumber(bone_ap_boost) <= 19 or tonumber(bone_ap_boost) == 14 then -- headshot bonus on unprotected parts
		if ammo_section == "ammo_12x70_buck" or ammo_section == "ammo_12x70_buck_bad" or
		   ammo_section == "ammo_20x70_buck" or ammo_section == "ammo_23x75_shrapnel" then
			k_ap = ( k_ap + 0.019 )
		else
			k_ap = ( k_ap + 0.040 )
		end
	end

	local k_ap = k_ap * custom_bone_ap_scale * barrel_condition_corrected -- reduce bullet ap following npc ap scale and barrel condition

	k_ap = k_ap / ( 1 + dist / 200 * ( air_res * 0.5 / ( 1 - air_res + 0.1 ))) * isg_res * silencer_boost * difficulty_multiplier[game_num] * invincible_mult * 0.80 -- last multiplier is a new adjustment after the bone grouping update

	shit.power = wpn_hit_power / ( 1 + dist / 200 * ( air_res * 0.5 / ( 1 - air_res + 0.1 ))) * k_hit * custom_bone_dmg_mult * custom_bone_ap_scale * 1.1 * sniper_bad_bone_shit_reduce * barrel_condition_corrected * sin_res * difficulty_multiplier[game_num] * ammo_mult * silencer_boost

	-- etapomom: run pba before armor so that they actually feel like they're doing something.
	pbadamage = hit(shit)
	PBA_obh(npc, pbadamage, bone_id, flags)
	shit.power = pbadamage.power
	
	local armor_loss_increment = tonumber(k_ap * 0.60) -- reduce bone armor depending on k_ap
	
	local new_bone_armor = tonumber( tonumber(custom_bone_armor) - tonumber(armor_loss_increment) )-- armor reduce
	custom_bone_value[custom_bone_id] = new_bone_armor
	
	if k_ap < custom_bone_armor then
		local new_bone_armor = tonumber( tonumber(custom_bone_armor) - tonumber(armor_loss_increment) )-- armor reduce
		custom_bone_value[custom_bone_id] = new_bone_armor
		if k_ap > new_bone_armor then -- if bullet damaged armor enough and pen with reduced power
			shit.power = shit.power * custom_bone_hitfraction
		else
			shit.power = 0.0025 * shit.power * custom_bone_hitfraction * math.random(25,100) / hp_no_penetration_penalty -- residual concussion damage if bullet didn't damage armor enough, the bigger the ammo the bigger the residual damages
			pos = npc:bone_position(custom_bone_name)
			fx = particles_object("hit_fx\\hit_metal_0" .. math.random(0,3))
			fxdir = shit.direction
			fxdir.x = (fxdir.x * -1.0) + math.random(-0.009, 0.009)
			fxdir.y = fxdir.y + math.random(-0.0045, 0.0045)
			fxdir.z = (fxdir.z * -1.0) + math.random(-0.009, 0.009)
			fx:set_direction(fxdir)
			camdir = device().cam_pos:add(device().cam_dir:mul(dist))
			pos.x = pos.x + (camdir.x * -0.0005)
			pos.z = pos.z + (camdir.z * -0.0005)
			fx:play_at_pos(pos)
		end
	else
		custom_bone_value[custom_bone_id] = custom_bone_armor
	end
	
	-- Add even more feedback on headshots
	if (k_ap > new_bone_armor) and headBones[bone_id] then
		fx = particles_object("anomaly2\\effects\\body_tear_blood_01")
		pos = npc:bone_position(custom_bone_name)
		fx:play_at_pos(pos)
	end
	
	-- Double the damage if the NPC is wounded
	-- This is for having better bonuses from PBA as wounded NPCs die instantly anyways.
	if surrender_bonus == 1 then
		shit.power = shit.power * 2
	end
	
	life_remove = shit.power * invincible_mult
	
	if surrender_bonus == 1 then
		npc:set_health_ex(0.0)
	else
		npc:set_health_ex(npc.health - life_remove)
	end
	
	-- etapomom: fire on_death_callback and or on_hit_callback from pba
	if npc.health <= 0 then
		PBA_odc(npc, shit.draftsman)
	end
	
	PBA_ohc(npc, shit.power, shit.direction, shit.draftsman, bone_id)

	printf("Real AP power= %s, Bone armor after hit= %s, Damages inflicted= %s, Remaining health= %s", k_ap, custom_bone_value[custom_bone_id], life_remove, npc.health)
	
--	if life_remove < -1 then
--		if head_bones[bone_id] then
--			target_bone = "bip01_head"
--		end
		
--		if target_bone and math.random(1,10) >= 8 then
--			npc:set_bone_visible(target_bone, false, true)
--			play_particle(npc, 15, "hit_fx\\effects\\hit_blood_drops_hd_dust_18_extra")
--			play_particle(npc, 15,  "hit_fx\\effects\\hit_blood_drops_hd_dust_20")
--			play_particle(npc, 15,  "hit_fx\\effects\\hit_bb_07")
--			play_sound("gore\\hit_zombie_"..math.random(23), 1.2, npc)
--		end
--	end
	
	shit.power = 0.0001
	life_remove = nil
end

function on_game_start()
	RegisterScriptCallback("npc_on_before_hit",npc_on_before_hit)
	RegisterScriptCallback("monster_on_before_hit",monster_on_before_hit)
end



function play_particle(npc, bone_id, name)
    bone_id = (not bone_id or bone_id == 65535) and 1 or bone_id
    bone_name = head_bones[bone_id] or "bip01_spine"
    local particle = particles_object(name)
    local bone_pos = npc:bone_position(bone_name)
    
    if particle and not particle:playing() then
        particle:play_at_pos(bone_pos)
    end
end


function play_sound(snd, volume, npc)
	if not snd then
		return
	end
	local npc
	local snd = xr_sound.get_safe_sound_object(snd)
	if snd then
		snd:play(npc, 0, sound_object.s2d)
		snd.volume = volume or 1
		return snd
	end
end