-- Patch for Lower Weapon Sprint optimized and Quick Melee (Busyhands fix)
-- oleh5230, 12.05.26

lower_weapon_sprint.CreateTimeEvent = function(ev_id,act_id,timer,f,...)
	local params = {...}
	for i in pairs(params) do
		if type(params[i]) == "userdata" then
			local animation_slot = SYS_GetParam(2, params[i]:section(), "animation_slot", 0)
			if animation_slot == 13 then
				--printf("!lower_weapon_sprint.CreateTimeEvent intercepted, animation_slot: %s", animation_slot)
				return
			end
		end
	end
	--printf("lower_weapon_sprint.CreateTimeEvent")
	CreateTimeEvent(ev_id,act_id,timer,f,...)
end