local function on_game_load()
	
	if has_alife_info("x16_restr_release") then
		return
	end
	
	for i=1, 65534 do
		
		local sobj = alife_object(i)
		
		if sobj and sobj:name() == "yan_attack_zombies_space_restrictor" then
			
			alife_release(sobj, true)
			give_info("x16_restr_release")
			
			break
		
		end
		
	end
	
end

function on_game_start()
	RegisterScriptCallback("on_game_load", on_game_load)
end