-- Weapon Cover Tilt intercept to ignore phantoms
-- oleh5230, 05.07.25

local get_target_obj = level.get_target_obj

function ignore_phantoms(wpn, flags)
	local target_obj = get_target_obj()
	if target_obj and target_obj:clsid() == clsid.phantom then
		flags.enabled = false
	end
end

function on_game_start()
	if weapon_cover_tilt then weapon_cover_tilt.add_callback("actor_on_weapon_before_tilt", ignore_phantoms) end
end