-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets
    
	o["wpn_mossberg590"] = {
		y = 0.2,
	}
      o["wpn_mossberg590_wood"] = {
		y = 0.2,
      }
      o["wpn_mossberg590_rail"] = {
		y = 0.2,
      }
end