-- Extension script for weapon_cover_tilt_positions.script file
-- Open weapon_cover_tilt_positions.script file for instructions

if weapon_cover_tilt_positions then

	if not weapon_cover_tilt_positions.weapon_offsets then
		weapon_cover_tilt_positions.weapon_offsets = {}
	end
	
	local o = weapon_cover_tilt_positions.weapon_offsets

	o["wpn_saiga12s_m1"] = {
		x = 0.07,
		y = 0.52,
		z = 0.2,
	}
	o["wpn_saiga12s_m2"] = {
		x = 0.07,
		y = 0.52,
		z = 0.2,
	}

end