
z_item_icon_info_Add_Condition_Text = z_item_icon_info.Add_Condition_Text

function z_item_icon_info.Add_Condition_Text(self, xml, obj, sec, clsid)
	if  obj and IsWeapon(obj) and not IsMelee(obj) then
		if  self.cond_text then
			self.cond_text:Show(false)
		end
		if  self.cond_text_bg then
			self.cond_text_bg:Show(false)
		end
		return
    end
    z_item_icon_info_Add_Condition_Text(self, xml, obj, sec, clsid)
end