function on_mcm_load()
	options = {
		id = "remember_outfit_belt", 
		sh = true,
		gr = {
            { id = "title", type = "slide", link = "ui_options_slider_disguise", text = "ui_mcm_remember_outfit_belt_title", size = {512,50}, spacing= 20 },
			{ id = "title_desc", type = "desc", text = "ui_mcm_remember_outfit_belt_title_desc" },

            { id = "memory_limit", type = "track", val = 2, min = 1, max = 10, step = 1, def = 5},
		}
	}

	return options
end