
function on_mcm_load()
		op = { id= "EA_settings"      	 	,sh=true ,gr={
				{ id= "friendlyfire"				 ,type= "slide"	  ,link= "ui_options_slider_disguise"	 ,text= "FDDA"		,size= {512,50}		,spacing= 20 },
				{id = "enable_animations", type = "check", val = 1, def = true},
--				{id = "enable_backpack_addon", type = "check", val = 1, def = false},
--				{id = "enable_crouch_toggle_backpack_addon", type = "check", val = 1, def = false},
				{id = "mutant_loot", type = "check", val = 1, def = true},
--				{id = "take_item_anim", type = "check", val = 1, def = false},
				{id = "ea_debug", type = "check", val = 1, def = false},
				}
			}

		return op
end
