
function on_game_start()
	RegisterScriptCallback("GUI_on_show", set_player_icon)
end 

function set_player_icon()
	if (ui_options.get("gameplay/general/outfit_portrait") == true) then
		if (db.actor) then
			local outfit = db.actor:item_in_slot(7)
			if (outfit) then
				local icon = ini_sys:r_string_ex(outfit:section(),"character_portrait")
				if (icon) then
					db.actor:set_character_icon(icon)
				end
			end
		end

	end
	UnregisterScriptCallback("GUI_on_show", set_player_icon)
end