-- Artefacts spawn for DAO
-- Artefacts spawn by this procedure
-- 1. Get current level
-- 2. Get available artefacts for current level
-- 2. Iterate through anomaly zones
-- 3. If anomaly zone has entry in anomaly_type_to_artefacts table, filter artefacts for this zone
-- 4. Pick either random artefact from artefacts for current level or all allowed artefacts. This allows to have some variety in spawns and support for extra artefacts mods
-- 5. Spawn artefact somewhere in the zone

-- Build a table of allowed artefacts
allowed_artefacts = (function() -- Allowed artefacts to spawn
	local allow_artefacts = (function()
		local t = {}
		ini_sys:section_for_each(function(sec)
			if SYS_GetParam(0, sec, "kind", "") == "i_arty" then -- Allow artefacts
				t[sec] = true
			elseif SYS_GetParam(0, sec, "kind", "") == "i_arty_junk" then -- Allow junk artefacts
				t[sec] = true
			end
		end)
		return t
	end)()

	local ignore_artefacts = (function()
		local t = {}
		t["af_lucifer"] = true -- PBA
		t["af_fire_loop"] = true -- GAMMA
		t["af_full_empty"] = true -- GAMMA
		t["af_compass"] = true -- GAMMA
		
		t["af_ah_e1"] = true -- AH
		t["af_ah_e2"] = true -- AH
		t["af_ah_f1"] = true -- AH
		t["af_ah_g1"] = true -- AH
		t["af_ah_g2"] = true -- AH
		t["af_ah_h1"] = true -- AH
		t["af_ah_h2"] = true -- AH
		t["af_ah_o1"] = true -- AH
		t["af_ah_o2"] = true -- AH
		t["af_ah_r1"] = true -- AH
		t["af_ah_r2"] = true -- AH
		t["af_ah_r3"] = true -- AH
		t["af_ah_r4"] = true -- AH
		t["af_ah_r5"] = true -- AH
		t["af_ah_s1"] = true -- AH
		
		-- Multiplayer items
		t["mp_af_electra_flash"] = true
		t["mp_zone_witches_galantine"] = true
		t["mp_af_cta_green"] = true
		t["mp_af_cta_blue"] = true
		t["mp_medkit"] = true
		t["mp_medkit_scientic"] = true
		t["mp_medkit_army"] = true
		t["mp_energy_drink"] = true
		t["mp_bandage"] = true
		t["mp_antirad"] = true
		t["mp_drug_coagulant"] = true
		t["mp_drug_radioprotector"] = true
		t["mp_medkit_old"] = true
		t["mp_antirad_old"] = true
		t["mp_detector_advanced"] = true
		t["mp_device_torch"] = true
		t["mp_players_rukzak"] = true
		t["mp_wood_stolb_fixed"] = true
		t["mp_wood_stolb_fixed_immunities"] = true
		t["mp_explosive_fuelcan"] = true
		t["mp_explosive_tank"] = true
		t["mp_explosive_barrel"] = true

		-- Unique artefacts
		t["af_ameba_mica"] = true
		t["af_ameba_slime"] = true
		t["af_ameba_slug"] = true
		t["af_base_mlr"] = true
		t["af_black"] = true
		t["af_control"] = true
		t["af_drops"] = true
		t["af_dummy_pellicle"] = true
		t["af_dummy_spring"] = true
		t["af_geliy"] = true
		t["af_gimlet"] = true
		t["af_monolith"] = true
		t["af_oasis_heart"] = true
		t["af_quest_b14_twisted"] = true
		t["af_rusty_kristall"] = true
		t["af_rusty_sea"] = true
		t["af_rusty_thorn"] = true
		t["af_vaselisk"] = true
		t["jup_b1_half_artifact"] = true
		t["marker"] = true
		t["monolith_shard"] = true
		
		
		ini_sys:section_for_each(function(sec)
			if SYS_GetParam(0, sec, "kind", "") == "i_arty_cont" then -- Exclude artefacts in containers
				t[sec] = true
			elseif SYS_GetParam(0, sec, "kind", "") == "i_attach" then -- Exclude attachments
				t[sec] = true
			elseif SYS_GetParam(0, sec, "kind", "") == "i_quest" then -- Exclude quest items
				t[sec] = true
			elseif SYS_GetParam(0, sec, "kind", "") == "i_mutant_belt" then -- Exclude mutant hides
				t[sec] = true
			elseif SYS_GetParam(1, sec, "quest_item", false) then -- Exclude quest items
				t[sec] = true
			end
		end)
		return t
	end)()

	local t = {}
	for k, v in pairs(allow_artefacts) do
		if not ignore_artefacts[k] then
			t[#t + 1] = k
		end
	end
	return t
end)()

-- Table of artefacts chances per level
-- If defined, the chances from table will be used instead of default ones or from MCM

artefacts_map_chances = {
	["k00_marsh"] = 20,
	["l01_escape"] = 20,
	["l02_garbage"] = 20,
	["y04_pole"] = 28,
	["l05_bar"] = 0,
	["l03_agroprom"] = 20,
	["k01_darkscape"] = 20,
	["l04_darkvalley"] = 20,
	["k02_trucks_cemetery"] = 28,
	["l06_rostok"] = 25,
	["l07_military"] = 20,
	["l09_deadcity"] = 20,
	["l08_yantar"] = 20,
	["l03u_agr_underground"] = 20,
	["jupiter"] = 20,
	["l10_limansk"] = 30,
	["l04u_labx18"] = 30,
	["l10_red_forest"] = 35,
	["l08u_brainlab"] = 30,
	["l10_radar"] = 35,
	["l10u_bunker"] = 30,
	["l11_hospital"] = 30,
	["l12_stancia"] = 30,
	["l12_stancia_2"] = 30,
	["l12u_control_monolith"] = 30,
	["l12u_sarcofag"] = 30,
	["l13_generators"] = 30,
	["l13u_warlab"] = 30,
	["labx8"] = 30,
	["pripyat"] = 30,
}

-- Table of artefacts per level
artefacts_map_tiers = {
	["k00_marsh"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l01_escape"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l05_bar"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l02_garbage"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["k01_darkscape"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l04_darkvalley"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
	},
		
	["k02_trucks_cemetery"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
	},
		
	["l09_deadcity"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l03_agroprom"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l06_rostok"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["l07_military"] = {
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
	},
		
	["l08_yantar"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
		
	["jupiter"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
	},
		
	["l03u_agr_underground"] = {
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		
		"af_bat",
	},
		
	["l10_limansk"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		
		"af_bat",
	},
		
	["l08u_brainlab"] = {
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray","af_gold_fish",
		
		"af_bat",
	},
		
	["l10_red_forest"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		
		"af_bat",
	},
		
	["labx8"] = {
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},

	["l12_stancia"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
	},
	
	["zaton"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
	},
	
	["l12_stancia_2"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
	},
	
	["l11_hospital"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
	},
	
	["jupiter_underground"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	
	["l10u_bunker"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
	},
	
	["l10_radar"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	["l04u_labx18"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		"af_bat",
	},
	
	["l11_pripyat"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	["l12u_sarcofag"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	["l12u_control_monolith"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	["l13_generators"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
		
	["l13u_warlab"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	["pripyat"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",

		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
		
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
		"af_vyvert","af_empty","af_pin","af_cristall","af_lobster_eyes","af_gravi","af_ring","af_electra_moonlight","af_sponge","af_bracelet","af_fuzz_kolobok","af_eye","af_dummy_dummy",
			
		"af_fireball","af_fire","af_electra_flash","af_ice","af_baloon","af_glass","af_black_spray",
		
		"af_bat",
	},
	
	["y04_pole"] = {
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_spaika","af_cocoon","af_sandstone","af_cell","af_dragon_eye","af_kislushka", "af_sun","af_tapeworm","af_skull_miser","af_repei","af_moh","af_ball","af_generator","af_elektron","af_kogot","af_grapes","af_kislushka","af_signet","af_black_angel","af_ear","af_zhelch",
		"af_medusa","af_itcher","af_dummy_glassbeads","af_night_star","af_mincer_meat","af_dummy_battery","af_electra_sparkler","af_blood","af_cristall_flower","af_soul",
	},
}

-- Table of artefacts belonging to anomaly types
-- Its optional, if anomaly type isn't found, picked artefact will be random from current level spawns 
anomaly_type_to_artefacts = {

}
