local defaults = {
    ["enabled"] = true,
}

function get_config(key)
    if ui_mcm then return ui_mcm.get("grok_artefacts_bip/"..key) else return defaults[key] end
end

function on_mcm_load()
    op = { id= "grok_artefacts_bip",sh=true ,gr={
            { id= "title",type= "slide",link= "ui_options_slider_player",text="ui_mcm_grok_artefacts_bip_title",size= {512,50},spacing= 20 },
            {id = "enabled", type = "check", val = 1, def = true}
        }
    }
    return op
end