arti_min_eff = 5
arti_max_eff = 20


function grok_arti_random_efficiency(obj)
	kind = SYS_GetParam(0, obj:section(), "kind")
	if (obj:condition() == 1 and kind == "i_arty") then
		cond = (math.random(arti_min_eff, arti_max_eff) / 100)
		obj:set_condition(cond)
	end

end

function on_game_start()
	RegisterScriptCallback("actor_item_to_ruck", grok_arti_random_efficiency)
	RegisterScriptCallback("actor_on_item_take", grok_arti_random_efficiency)
end